/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { PostPrintPreview200, PostPrintPreviewBody } from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getPrintPreview = () => {
  /**
   * Generate HTML preview for a document using a print template
   * @summary Preview document as HTML
   */
  const postPrintPreview = (
    postPrintPreviewBody: PostPrintPreviewBody,
    options?: SecondParameter<typeof customInstance<PostPrintPreview200>>
  ) => {
    return customInstance<PostPrintPreview200>(
      {
        url: `/print/preview`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postPrintPreviewBody,
      },
      options
    )
  }
  return { postPrintPreview }
}
export type PostPrintPreviewResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPrintPreview>['postPrintPreview']>>
>
