/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DeleteTradePurchaseOrdersIdItemsItemId200,
  GetTradePurchaseOrders200,
  GetTradePurchaseOrdersId200,
  GetTradePurchaseOrdersIdReceivableItems200,
  GetTradePurchaseOrdersNumberOrderNumber200,
  GetTradePurchaseOrdersParams,
  GetTradePurchaseOrdersPendingReceipt200,
  GetTradePurchaseOrdersPendingReceiptParams,
  GetTradePurchaseOrdersStatsSummary200,
  HandlerAddPurchaseOrderItemRequest,
  HandlerCancelPurchaseOrderRequest,
  HandlerConfirmPurchaseOrderRequest,
  HandlerCreatePurchaseOrderRequest,
  HandlerReceivePurchaseOrderRequest,
  HandlerUpdatePurchaseOrderItemRequest,
  HandlerUpdatePurchaseOrderRequest,
  PostTradePurchaseOrders201,
  PostTradePurchaseOrdersIdCancel200,
  PostTradePurchaseOrdersIdConfirm200,
  PostTradePurchaseOrdersIdItems200,
  PostTradePurchaseOrdersIdReceive200,
  PutTradePurchaseOrdersId200,
  PutTradePurchaseOrdersIdItemsItemId200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getPurchaseOrders = () => {
  /**
   * Retrieve a paginated list of purchase orders with optional filtering
   * @summary List purchase orders
   */
  const getTradePurchaseOrders = (
    params?: GetTradePurchaseOrdersParams,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseOrders200>>
  ) => {
    return customInstance<GetTradePurchaseOrders200>(
      { url: `/trade/purchase-orders`, method: 'GET', params },
      options
    )
  }
  /**
   * Create a new purchase order with optional items
   * @summary Create a new purchase order
   */
  const postTradePurchaseOrders = (
    handlerCreatePurchaseOrderRequest: HandlerCreatePurchaseOrderRequest,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseOrders201>>
  ) => {
    return customInstance<PostTradePurchaseOrders201>(
      {
        url: `/trade/purchase-orders`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreatePurchaseOrderRequest,
      },
      options
    )
  }
  /**
   * Delete a purchase order (only allowed in DRAFT status)
   * @summary Delete a purchase order
   */
  const deleteTradePurchaseOrdersId = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>({ url: `/trade/purchase-orders/${id}`, method: 'DELETE' }, options)
  }
  /**
   * Retrieve a purchase order by its ID
   * @summary Get purchase order by ID
   */
  const getTradePurchaseOrdersId = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseOrdersId200>>
  ) => {
    return customInstance<GetTradePurchaseOrdersId200>(
      { url: `/trade/purchase-orders/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update a purchase order (only allowed in DRAFT status)
   * @summary Update a purchase order
   */
  const putTradePurchaseOrdersId = (
    id: string,
    handlerUpdatePurchaseOrderRequest: HandlerUpdatePurchaseOrderRequest,
    options?: SecondParameter<typeof customInstance<PutTradePurchaseOrdersId200>>
  ) => {
    return customInstance<PutTradePurchaseOrdersId200>(
      {
        url: `/trade/purchase-orders/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdatePurchaseOrderRequest,
      },
      options
    )
  }
  /**
   * Cancel a purchase order (only from DRAFT or CONFIRMED status)
   * @summary Cancel a purchase order
   */
  const postTradePurchaseOrdersIdCancel = (
    id: string,
    handlerCancelPurchaseOrderRequest: HandlerCancelPurchaseOrderRequest,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseOrdersIdCancel200>>
  ) => {
    return customInstance<PostTradePurchaseOrdersIdCancel200>(
      {
        url: `/trade/purchase-orders/${id}/cancel`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCancelPurchaseOrderRequest,
      },
      options
    )
  }
  /**
   * Confirm a purchase order (transitions from DRAFT to CONFIRMED)
   * @summary Confirm a purchase order
   */
  const postTradePurchaseOrdersIdConfirm = (
    id: string,
    handlerConfirmPurchaseOrderRequest: HandlerConfirmPurchaseOrderRequest,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseOrdersIdConfirm200>>
  ) => {
    return customInstance<PostTradePurchaseOrdersIdConfirm200>(
      {
        url: `/trade/purchase-orders/${id}/confirm`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerConfirmPurchaseOrderRequest,
      },
      options
    )
  }
  /**
   * Add a new item to a purchase order (only allowed in DRAFT status)
   * @summary Add item to purchase order
   */
  const postTradePurchaseOrdersIdItems = (
    id: string,
    handlerAddPurchaseOrderItemRequest: HandlerAddPurchaseOrderItemRequest,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseOrdersIdItems200>>
  ) => {
    return customInstance<PostTradePurchaseOrdersIdItems200>(
      {
        url: `/trade/purchase-orders/${id}/items`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerAddPurchaseOrderItemRequest,
      },
      options
    )
  }
  /**
   * Remove an item from a purchase order (only allowed in DRAFT status)
   * @summary Remove item from purchase order
   */
  const deleteTradePurchaseOrdersIdItemsItemId = (
    id: string,
    itemId: string,
    options?: SecondParameter<typeof customInstance<DeleteTradePurchaseOrdersIdItemsItemId200>>
  ) => {
    return customInstance<DeleteTradePurchaseOrdersIdItemsItemId200>(
      { url: `/trade/purchase-orders/${id}/items/${itemId}`, method: 'DELETE' },
      options
    )
  }
  /**
   * Update an item in a purchase order (only allowed in DRAFT status)
   * @summary Update order item
   */
  const putTradePurchaseOrdersIdItemsItemId = (
    id: string,
    itemId: string,
    handlerUpdatePurchaseOrderItemRequest: HandlerUpdatePurchaseOrderItemRequest,
    options?: SecondParameter<typeof customInstance<PutTradePurchaseOrdersIdItemsItemId200>>
  ) => {
    return customInstance<PutTradePurchaseOrdersIdItemsItemId200>(
      {
        url: `/trade/purchase-orders/${id}/items/${itemId}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdatePurchaseOrderItemRequest,
      },
      options
    )
  }
  /**
   * Get items that can still receive goods for a purchase order
   * @summary Get receivable items for a purchase order
   */
  const getTradePurchaseOrdersIdReceivableItems = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseOrdersIdReceivableItems200>>
  ) => {
    return customInstance<GetTradePurchaseOrdersIdReceivableItems200>(
      { url: `/trade/purchase-orders/${id}/receivable-items`, method: 'GET' },
      options
    )
  }
  /**
   * Process receipt of goods for a purchase order (supports partial receipt)
   * @summary Receive goods for a purchase order
   */
  const postTradePurchaseOrdersIdReceive = (
    id: string,
    handlerReceivePurchaseOrderRequest: HandlerReceivePurchaseOrderRequest,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseOrdersIdReceive200>>
  ) => {
    return customInstance<PostTradePurchaseOrdersIdReceive200>(
      {
        url: `/trade/purchase-orders/${id}/receive`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerReceivePurchaseOrderRequest,
      },
      options
    )
  }
  /**
   * Retrieve a purchase order by its order number
   * @summary Get purchase order by order number
   */
  const getTradePurchaseOrdersNumberOrderNumber = (
    orderNumber: string,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseOrdersNumberOrderNumber200>>
  ) => {
    return customInstance<GetTradePurchaseOrdersNumberOrderNumber200>(
      { url: `/trade/purchase-orders/number/${orderNumber}`, method: 'GET' },
      options
    )
  }
  /**
   * Retrieve purchase orders that are waiting to receive goods (CONFIRMED or PARTIAL_RECEIVED)
   * @summary List purchase orders pending receipt
   */
  const getTradePurchaseOrdersPendingReceipt = (
    params?: GetTradePurchaseOrdersPendingReceiptParams,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseOrdersPendingReceipt200>>
  ) => {
    return customInstance<GetTradePurchaseOrdersPendingReceipt200>(
      { url: `/trade/purchase-orders/pending-receipt`, method: 'GET', params },
      options
    )
  }
  /**
   * Get count of purchase orders by status for dashboard
   * @summary Get purchase order status summary
   */
  const getTradePurchaseOrdersStatsSummary = (
    options?: SecondParameter<typeof customInstance<GetTradePurchaseOrdersStatsSummary200>>
  ) => {
    return customInstance<GetTradePurchaseOrdersStatsSummary200>(
      { url: `/trade/purchase-orders/stats/summary`, method: 'GET' },
      options
    )
  }
  return {
    getTradePurchaseOrders,
    postTradePurchaseOrders,
    deleteTradePurchaseOrdersId,
    getTradePurchaseOrdersId,
    putTradePurchaseOrdersId,
    postTradePurchaseOrdersIdCancel,
    postTradePurchaseOrdersIdConfirm,
    postTradePurchaseOrdersIdItems,
    deleteTradePurchaseOrdersIdItemsItemId,
    putTradePurchaseOrdersIdItemsItemId,
    getTradePurchaseOrdersIdReceivableItems,
    postTradePurchaseOrdersIdReceive,
    getTradePurchaseOrdersNumberOrderNumber,
    getTradePurchaseOrdersPendingReceipt,
    getTradePurchaseOrdersStatsSummary,
  }
}
export type GetTradePurchaseOrdersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['getTradePurchaseOrders']>>
>
export type PostTradePurchaseOrdersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['postTradePurchaseOrders']>>
>
export type DeleteTradePurchaseOrdersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['deleteTradePurchaseOrdersId']>>
>
export type GetTradePurchaseOrdersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['getTradePurchaseOrdersId']>>
>
export type PutTradePurchaseOrdersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['putTradePurchaseOrdersId']>>
>
export type PostTradePurchaseOrdersIdCancelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['postTradePurchaseOrdersIdCancel']>>
>
export type PostTradePurchaseOrdersIdConfirmResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['postTradePurchaseOrdersIdConfirm']>>
>
export type PostTradePurchaseOrdersIdItemsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['postTradePurchaseOrdersIdItems']>>
>
export type DeleteTradePurchaseOrdersIdItemsItemIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPurchaseOrders>['deleteTradePurchaseOrdersIdItemsItemId']>
  >
>
export type PutTradePurchaseOrdersIdItemsItemIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['putTradePurchaseOrdersIdItemsItemId']>>
>
export type GetTradePurchaseOrdersIdReceivableItemsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPurchaseOrders>['getTradePurchaseOrdersIdReceivableItems']>
  >
>
export type PostTradePurchaseOrdersIdReceiveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['postTradePurchaseOrdersIdReceive']>>
>
export type GetTradePurchaseOrdersNumberOrderNumberResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPurchaseOrders>['getTradePurchaseOrdersNumberOrderNumber']>
  >
>
export type GetTradePurchaseOrdersPendingReceiptResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['getTradePurchaseOrdersPendingReceipt']>>
>
export type GetTradePurchaseOrdersStatsSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseOrders>['getTradePurchaseOrdersStatsSummary']>>
>
