/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DtoResponse,
  GetIdentityUsers200,
  GetIdentityUsersId200,
  GetIdentityUsersParams,
  GetIdentityUsersStatsCount200,
  HandlerAssignRolesRequest,
  HandlerCreateUserRequest,
  HandlerLockUserRequest,
  HandlerResetPasswordRequest,
  HandlerUpdateUserRequest,
  PostIdentityUsers201,
  PostIdentityUsersIdActivate200,
  PostIdentityUsersIdDeactivate200,
  PostIdentityUsersIdLock200,
  PostIdentityUsersIdUnlock200,
  PutIdentityUsersId200,
  PutIdentityUsersIdRoles200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getUsers = () => {
  /**
   * Get a paginated list of users
   * @summary List users
   */
  const getIdentityUsers = (
    params?: GetIdentityUsersParams,
    options?: SecondParameter<typeof customInstance<GetIdentityUsers200>>
  ) => {
    return customInstance<GetIdentityUsers200>(
      { url: `/identity/users`, method: 'GET', params },
      options
    )
  }
  /**
   * Create a new user in the system
   * @summary Create a new user
   */
  const postIdentityUsers = (
    handlerCreateUserRequest: HandlerCreateUserRequest,
    options?: SecondParameter<typeof customInstance<PostIdentityUsers201>>
  ) => {
    return customInstance<PostIdentityUsers201>(
      {
        url: `/identity/users`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateUserRequest,
      },
      options
    )
  }
  /**
   * Delete a user from the system
   * @summary Delete a user
   */
  const deleteIdentityUsersId = (
    id: string,
    options?: SecondParameter<typeof customInstance<DtoResponse>>
  ) => {
    return customInstance<DtoResponse>({ url: `/identity/users/${id}`, method: 'DELETE' }, options)
  }
  /**
   * Retrieve a user by their ID
   * @summary Get a user by ID
   */
  const getIdentityUsersId = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetIdentityUsersId200>>
  ) => {
    return customInstance<GetIdentityUsersId200>(
      { url: `/identity/users/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update a user's information
   * @summary Update a user
   */
  const putIdentityUsersId = (
    id: string,
    handlerUpdateUserRequest: HandlerUpdateUserRequest,
    options?: SecondParameter<typeof customInstance<PutIdentityUsersId200>>
  ) => {
    return customInstance<PutIdentityUsersId200>(
      {
        url: `/identity/users/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateUserRequest,
      },
      options
    )
  }
  /**
   * Activate a user account
   * @summary Activate a user
   */
  const postIdentityUsersIdActivate = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostIdentityUsersIdActivate200>>
  ) => {
    return customInstance<PostIdentityUsersIdActivate200>(
      { url: `/identity/users/${id}/activate`, method: 'POST' },
      options
    )
  }
  /**
   * Deactivate a user account
   * @summary Deactivate a user
   */
  const postIdentityUsersIdDeactivate = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostIdentityUsersIdDeactivate200>>
  ) => {
    return customInstance<PostIdentityUsersIdDeactivate200>(
      { url: `/identity/users/${id}/deactivate`, method: 'POST' },
      options
    )
  }
  /**
   * Lock a user account for a specified duration
   * @summary Lock a user
   */
  const postIdentityUsersIdLock = (
    id: string,
    handlerLockUserRequest: HandlerLockUserRequest,
    options?: SecondParameter<typeof customInstance<PostIdentityUsersIdLock200>>
  ) => {
    return customInstance<PostIdentityUsersIdLock200>(
      {
        url: `/identity/users/${id}/lock`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerLockUserRequest,
      },
      options
    )
  }
  /**
   * Reset a user's password (admin action)
   * @summary Reset user password
   */
  const postIdentityUsersIdResetPassword = (
    id: string,
    handlerResetPasswordRequest: HandlerResetPasswordRequest,
    options?: SecondParameter<typeof customInstance<DtoResponse>>
  ) => {
    return customInstance<DtoResponse>(
      {
        url: `/identity/users/${id}/reset-password`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerResetPasswordRequest,
      },
      options
    )
  }
  /**
   * Assign roles to a user (replaces existing roles)
   * @summary Assign roles to a user
   */
  const putIdentityUsersIdRoles = (
    id: string,
    handlerAssignRolesRequest: HandlerAssignRolesRequest,
    options?: SecondParameter<typeof customInstance<PutIdentityUsersIdRoles200>>
  ) => {
    return customInstance<PutIdentityUsersIdRoles200>(
      {
        url: `/identity/users/${id}/roles`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerAssignRolesRequest,
      },
      options
    )
  }
  /**
   * Unlock a locked user account
   * @summary Unlock a user
   */
  const postIdentityUsersIdUnlock = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostIdentityUsersIdUnlock200>>
  ) => {
    return customInstance<PostIdentityUsersIdUnlock200>(
      { url: `/identity/users/${id}/unlock`, method: 'POST' },
      options
    )
  }
  /**
   * Get the total number of users
   * @summary Get user count
   */
  const getIdentityUsersStatsCount = (
    options?: SecondParameter<typeof customInstance<GetIdentityUsersStatsCount200>>
  ) => {
    return customInstance<GetIdentityUsersStatsCount200>(
      { url: `/identity/users/stats/count`, method: 'GET' },
      options
    )
  }
  return {
    getIdentityUsers,
    postIdentityUsers,
    deleteIdentityUsersId,
    getIdentityUsersId,
    putIdentityUsersId,
    postIdentityUsersIdActivate,
    postIdentityUsersIdDeactivate,
    postIdentityUsersIdLock,
    postIdentityUsersIdResetPassword,
    putIdentityUsersIdRoles,
    postIdentityUsersIdUnlock,
    getIdentityUsersStatsCount,
  }
}
export type GetIdentityUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['getIdentityUsers']>>
>
export type PostIdentityUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postIdentityUsers']>>
>
export type DeleteIdentityUsersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['deleteIdentityUsersId']>>
>
export type GetIdentityUsersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['getIdentityUsersId']>>
>
export type PutIdentityUsersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['putIdentityUsersId']>>
>
export type PostIdentityUsersIdActivateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postIdentityUsersIdActivate']>>
>
export type PostIdentityUsersIdDeactivateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postIdentityUsersIdDeactivate']>>
>
export type PostIdentityUsersIdLockResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postIdentityUsersIdLock']>>
>
export type PostIdentityUsersIdResetPasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postIdentityUsersIdResetPassword']>>
>
export type PutIdentityUsersIdRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['putIdentityUsersIdRoles']>>
>
export type PostIdentityUsersIdUnlockResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['postIdentityUsersIdUnlock']>>
>
export type GetIdentityUsersStatsCountResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['getIdentityUsersStatsCount']>>
>
