/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DtoResponse,
  GetFinanceIncomes200,
  GetFinanceIncomesId200,
  GetFinanceIncomesParams,
  GetFinanceIncomesSummary200,
  GetFinanceIncomesSummaryParams,
  HandlerCreateOtherIncomeRecordRequest,
  HandlerIncomeActionRequest,
  HandlerMarkIncomeReceivedRequest,
  HandlerUpdateOtherIncomeRecordRequest,
  PostFinanceIncomes201,
  PostFinanceIncomesIdCancel200,
  PostFinanceIncomesIdConfirm200,
  PostFinanceIncomesIdReceive200,
  PutFinanceIncomesId200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getIncomes = () => {
  /**
   * Get a paginated list of other income records
   * @summary List other income records
   */
  const getFinanceIncomes = (
    params?: GetFinanceIncomesParams,
    options?: SecondParameter<typeof customInstance<GetFinanceIncomes200>>
  ) => {
    return customInstance<GetFinanceIncomes200>(
      { url: `/finance/incomes`, method: 'GET', params },
      options
    )
  }
  /**
   * Create a new other income record
   * @summary Create other income record
   */
  const postFinanceIncomes = (
    handlerCreateOtherIncomeRecordRequest: HandlerCreateOtherIncomeRecordRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceIncomes201>>
  ) => {
    return customInstance<PostFinanceIncomes201>(
      {
        url: `/finance/incomes`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateOtherIncomeRecordRequest,
      },
      options
    )
  }
  /**
   * Delete an income record (soft delete, only draft status)
   * @summary Delete other income record
   */
  const deleteFinanceIncomesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<DtoResponse>>
  ) => {
    return customInstance<DtoResponse>({ url: `/finance/incomes/${id}`, method: 'DELETE' }, options)
  }
  /**
   * Get a single income record by its ID
   * @summary Get other income record by ID
   */
  const getFinanceIncomesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetFinanceIncomesId200>>
  ) => {
    return customInstance<GetFinanceIncomesId200>(
      { url: `/finance/incomes/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update an existing income record (only draft status)
   * @summary Update other income record
   */
  const putFinanceIncomesId = (
    id: string,
    handlerUpdateOtherIncomeRecordRequest: HandlerUpdateOtherIncomeRecordRequest,
    options?: SecondParameter<typeof customInstance<PutFinanceIncomesId200>>
  ) => {
    return customInstance<PutFinanceIncomesId200>(
      {
        url: `/finance/incomes/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateOtherIncomeRecordRequest,
      },
      options
    )
  }
  /**
   * Cancel an income record
   * @summary Cancel income record
   */
  const postFinanceIncomesIdCancel = (
    id: string,
    handlerIncomeActionRequest: HandlerIncomeActionRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceIncomesIdCancel200>>
  ) => {
    return customInstance<PostFinanceIncomesIdCancel200>(
      {
        url: `/finance/incomes/${id}/cancel`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerIncomeActionRequest,
      },
      options
    )
  }
  /**
   * Confirm an income record
   * @summary Confirm income record
   */
  const postFinanceIncomesIdConfirm = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostFinanceIncomesIdConfirm200>>
  ) => {
    return customInstance<PostFinanceIncomesIdConfirm200>(
      { url: `/finance/incomes/${id}/confirm`, method: 'POST' },
      options
    )
  }
  /**
   * Mark a confirmed income as received
   * @summary Mark income as received
   */
  const postFinanceIncomesIdReceive = (
    id: string,
    handlerMarkIncomeReceivedRequest: HandlerMarkIncomeReceivedRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceIncomesIdReceive200>>
  ) => {
    return customInstance<PostFinanceIncomesIdReceive200>(
      {
        url: `/finance/incomes/${id}/receive`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerMarkIncomeReceivedRequest,
      },
      options
    )
  }
  /**
   * Get income statistics summary
   * @summary Get incomes summary
   */
  const getFinanceIncomesSummary = (
    params?: GetFinanceIncomesSummaryParams,
    options?: SecondParameter<typeof customInstance<GetFinanceIncomesSummary200>>
  ) => {
    return customInstance<GetFinanceIncomesSummary200>(
      { url: `/finance/incomes/summary`, method: 'GET', params },
      options
    )
  }
  return {
    getFinanceIncomes,
    postFinanceIncomes,
    deleteFinanceIncomesId,
    getFinanceIncomesId,
    putFinanceIncomesId,
    postFinanceIncomesIdCancel,
    postFinanceIncomesIdConfirm,
    postFinanceIncomesIdReceive,
    getFinanceIncomesSummary,
  }
}
export type GetFinanceIncomesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['getFinanceIncomes']>>
>
export type PostFinanceIncomesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['postFinanceIncomes']>>
>
export type DeleteFinanceIncomesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['deleteFinanceIncomesId']>>
>
export type GetFinanceIncomesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['getFinanceIncomesId']>>
>
export type PutFinanceIncomesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['putFinanceIncomesId']>>
>
export type PostFinanceIncomesIdCancelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['postFinanceIncomesIdCancel']>>
>
export type PostFinanceIncomesIdConfirmResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['postFinanceIncomesIdConfirm']>>
>
export type PostFinanceIncomesIdReceiveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['postFinanceIncomesIdReceive']>>
>
export type GetFinanceIncomesSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getIncomes>['getFinanceIncomesSummary']>>
>
