/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  GetPartnerSuppliers200,
  GetPartnerSuppliersCodeCode200,
  GetPartnerSuppliersId200,
  GetPartnerSuppliersParams,
  GetPartnerSuppliersStatsCount200,
  HandlerCreateSupplierRequest,
  HandlerSetPaymentTermsRequest,
  HandlerSetRatingRequest,
  HandlerUpdateSupplierCodeRequest,
  HandlerUpdateSupplierRequest,
  PostPartnerSuppliers201,
  PostPartnerSuppliersIdActivate200,
  PostPartnerSuppliersIdBlock200,
  PostPartnerSuppliersIdDeactivate200,
  PutPartnerSuppliersId200,
  PutPartnerSuppliersIdCode200,
  PutPartnerSuppliersIdPaymentTerms200,
  PutPartnerSuppliersIdRating200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getSuppliers = () => {
  /**
   * Retrieve a paginated list of suppliers with optional filtering
   * @summary List suppliers
   */
  const getPartnerSuppliers = (
    params?: GetPartnerSuppliersParams,
    options?: SecondParameter<typeof customInstance<GetPartnerSuppliers200>>
  ) => {
    return customInstance<GetPartnerSuppliers200>(
      { url: `/partner/suppliers`, method: 'GET', params },
      options
    )
  }
  /**
   * Create a new supplier in the partner module
   * @summary Create a new supplier
   */
  const postPartnerSuppliers = (
    handlerCreateSupplierRequest: HandlerCreateSupplierRequest,
    options?: SecondParameter<typeof customInstance<PostPartnerSuppliers201>>
  ) => {
    return customInstance<PostPartnerSuppliers201>(
      {
        url: `/partner/suppliers`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateSupplierRequest,
      },
      options
    )
  }
  /**
   * Delete a supplier by ID
   * @summary Delete a supplier
   */
  const deletePartnerSuppliersId = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>({ url: `/partner/suppliers/${id}`, method: 'DELETE' }, options)
  }
  /**
   * Retrieve a supplier by its ID
   * @summary Get supplier by ID
   */
  const getPartnerSuppliersId = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetPartnerSuppliersId200>>
  ) => {
    return customInstance<GetPartnerSuppliersId200>(
      { url: `/partner/suppliers/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update an existing supplier's details
   * @summary Update a supplier
   */
  const putPartnerSuppliersId = (
    id: string,
    handlerUpdateSupplierRequest: HandlerUpdateSupplierRequest,
    options?: SecondParameter<typeof customInstance<PutPartnerSuppliersId200>>
  ) => {
    return customInstance<PutPartnerSuppliersId200>(
      {
        url: `/partner/suppliers/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateSupplierRequest,
      },
      options
    )
  }
  /**
   * Activate an inactive or blocked supplier
   * @summary Activate a supplier
   */
  const postPartnerSuppliersIdActivate = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostPartnerSuppliersIdActivate200>>
  ) => {
    return customInstance<PostPartnerSuppliersIdActivate200>(
      { url: `/partner/suppliers/${id}/activate`, method: 'POST' },
      options
    )
  }
  /**
   * Block a supplier from doing business
   * @summary Block a supplier
   */
  const postPartnerSuppliersIdBlock = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostPartnerSuppliersIdBlock200>>
  ) => {
    return customInstance<PostPartnerSuppliersIdBlock200>(
      { url: `/partner/suppliers/${id}/block`, method: 'POST' },
      options
    )
  }
  /**
   * Update a supplier's code
   * @summary Update supplier code
   */
  const putPartnerSuppliersIdCode = (
    id: string,
    handlerUpdateSupplierCodeRequest: HandlerUpdateSupplierCodeRequest,
    options?: SecondParameter<typeof customInstance<PutPartnerSuppliersIdCode200>>
  ) => {
    return customInstance<PutPartnerSuppliersIdCode200>(
      {
        url: `/partner/suppliers/${id}/code`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateSupplierCodeRequest,
      },
      options
    )
  }
  /**
   * Deactivate an active supplier
   * @summary Deactivate a supplier
   */
  const postPartnerSuppliersIdDeactivate = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostPartnerSuppliersIdDeactivate200>>
  ) => {
    return customInstance<PostPartnerSuppliersIdDeactivate200>(
      { url: `/partner/suppliers/${id}/deactivate`, method: 'POST' },
      options
    )
  }
  /**
   * Set a supplier's credit days and credit limit
   * @summary Set supplier payment terms
   */
  const putPartnerSuppliersIdPaymentTerms = (
    id: string,
    handlerSetPaymentTermsRequest: HandlerSetPaymentTermsRequest,
    options?: SecondParameter<typeof customInstance<PutPartnerSuppliersIdPaymentTerms200>>
  ) => {
    return customInstance<PutPartnerSuppliersIdPaymentTerms200>(
      {
        url: `/partner/suppliers/${id}/payment-terms`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerSetPaymentTermsRequest,
      },
      options
    )
  }
  /**
   * Set a supplier's rating (0-5)
   * @summary Set supplier rating
   */
  const putPartnerSuppliersIdRating = (
    id: string,
    handlerSetRatingRequest: HandlerSetRatingRequest,
    options?: SecondParameter<typeof customInstance<PutPartnerSuppliersIdRating200>>
  ) => {
    return customInstance<PutPartnerSuppliersIdRating200>(
      {
        url: `/partner/suppliers/${id}/rating`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerSetRatingRequest,
      },
      options
    )
  }
  /**
   * Retrieve a supplier by its code
   * @summary Get supplier by code
   */
  const getPartnerSuppliersCodeCode = (
    code: string,
    options?: SecondParameter<typeof customInstance<GetPartnerSuppliersCodeCode200>>
  ) => {
    return customInstance<GetPartnerSuppliersCodeCode200>(
      { url: `/partner/suppliers/code/${code}`, method: 'GET' },
      options
    )
  }
  /**
   * Get the count of suppliers grouped by status
   * @summary Get supplier counts by status
   */
  const getPartnerSuppliersStatsCount = (
    options?: SecondParameter<typeof customInstance<GetPartnerSuppliersStatsCount200>>
  ) => {
    return customInstance<GetPartnerSuppliersStatsCount200>(
      { url: `/partner/suppliers/stats/count`, method: 'GET' },
      options
    )
  }
  return {
    getPartnerSuppliers,
    postPartnerSuppliers,
    deletePartnerSuppliersId,
    getPartnerSuppliersId,
    putPartnerSuppliersId,
    postPartnerSuppliersIdActivate,
    postPartnerSuppliersIdBlock,
    putPartnerSuppliersIdCode,
    postPartnerSuppliersIdDeactivate,
    putPartnerSuppliersIdPaymentTerms,
    putPartnerSuppliersIdRating,
    getPartnerSuppliersCodeCode,
    getPartnerSuppliersStatsCount,
  }
}
export type GetPartnerSuppliersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['getPartnerSuppliers']>>
>
export type PostPartnerSuppliersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['postPartnerSuppliers']>>
>
export type DeletePartnerSuppliersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['deletePartnerSuppliersId']>>
>
export type GetPartnerSuppliersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['getPartnerSuppliersId']>>
>
export type PutPartnerSuppliersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['putPartnerSuppliersId']>>
>
export type PostPartnerSuppliersIdActivateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['postPartnerSuppliersIdActivate']>>
>
export type PostPartnerSuppliersIdBlockResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['postPartnerSuppliersIdBlock']>>
>
export type PutPartnerSuppliersIdCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['putPartnerSuppliersIdCode']>>
>
export type PostPartnerSuppliersIdDeactivateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['postPartnerSuppliersIdDeactivate']>>
>
export type PutPartnerSuppliersIdPaymentTermsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['putPartnerSuppliersIdPaymentTerms']>>
>
export type PutPartnerSuppliersIdRatingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['putPartnerSuppliersIdRating']>>
>
export type GetPartnerSuppliersCodeCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['getPartnerSuppliersCodeCode']>>
>
export type GetPartnerSuppliersStatsCountResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuppliers>['getPartnerSuppliersStatsCount']>>
>
