/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerAddPurchaseReturnItemRequest } from './handlerAddPurchaseReturnItemRequest'

export type AddPurchaseReturnItemBody =
  | { [key: string]: unknown }
  | HandlerAddPurchaseReturnItemRequest
