/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerAddOrderItemRequest } from './handlerAddOrderItemRequest'

export type AddSalesOrderItemBody = { [key: string]: unknown } | HandlerAddOrderItemRequest
