/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerSuspendTenantRequest } from './handlerSuspendTenantRequest'

export type AdminSuspendTenantBody = { [key: string]: unknown } | HandlerSuspendTenantRequest
