/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type AdminListAuditLogsAction =
  (typeof AdminListAuditLogsAction)[keyof typeof AdminListAuditLogsAction]

export const AdminListAuditLogsAction = {
  tenant_create: 'tenant_create',
  tenant_update: 'tenant_update',
  tenant_delete: 'tenant_delete',
  tenant_suspend: 'tenant_suspend',
  tenant_activate: 'tenant_activate',
  subscription_change: 'subscription_change',
  quota_update: 'quota_update',
} as const
