/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerBatchSuspendRequest } from './handlerBatchSuspendRequest'

export type AdminPreviewBatchSuspendBody = { [key: string]: unknown } | HandlerBatchSuspendRequest
