/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerBatchDeleteRequest } from './handlerBatchDeleteRequest'

export type AdminBatchDeleteBody = { [key: string]: unknown } | HandlerBatchDeleteRequest
