/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerApprovePurchaseReturnRequest } from './handlerApprovePurchaseReturnRequest'

export type ApprovePurchaseReturnBody =
  | { [key: string]: unknown }
  | HandlerApprovePurchaseReturnRequest
