/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerBatchEvaluateHTTPRequest } from './handlerBatchEvaluateHTTPRequest'

export type BatchEvaluateFeatureFlagBody =
  | { [key: string]: unknown }
  | HandlerBatchEvaluateHTTPRequest
