/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export interface BulkImportErrorDetail {
  code?: string
  column?: string
  message?: string
  row?: number
  value?: string
}
