/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCreateCategoryRequest } from './handlerCreateCategoryRequest'

export type CreateCategoryBody = { [key: string]: unknown } | HandlerCreateCategoryRequest
