/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCreateOtherIncomeRecordRequest } from './handlerCreateOtherIncomeRecordRequest'

export type CreateIncomeIncomeBody =
  | { [key: string]: unknown }
  | HandlerCreateOtherIncomeRecordRequest
