/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type CsvimportImportState = (typeof CsvimportImportState)[keyof typeof CsvimportImportState]

export const CsvimportImportState = {
  StateCreated: 'created',
  StateValidating: 'validating',
  StateValidated: 'validated',
  StateImporting: 'importing',
  StateCompleted: 'completed',
  StateFailed: 'failed',
  StateCancelled: 'cancelled',
} as const
