/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoValidationDetail } from './dtoValidationDetail'

export interface DtoErrorInfo {
  code?: string
  details?: DtoValidationDetail[]
  help?: string
  message?: string
  request_id?: string
  timestamp?: string
}
