/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoFlagClientConfig } from './dtoFlagClientConfig'

export type DtoGetClientConfigResponseFlags = { [key: string]: DtoFlagClientConfig }
