/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetCatalogCategoriesStatus =
  (typeof GetCatalogCategoriesStatus)[keyof typeof GetCatalogCategoriesStatus]

export const GetCatalogCategoriesStatus = {
  active: 'active',
  inactive: 'inactive',
} as const
