/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetCatalogProductsStatus =
  (typeof GetCatalogProductsStatus)[keyof typeof GetCatalogProductsStatus]

export const GetCatalogProductsStatus = {
  active: 'active',
  inactive: 'inactive',
  discontinued: 'discontinued',
} as const
