/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerAuditLogResponse } from './handlerAuditLogResponse'

export type GetFinanceTrialBalanceAuditLogs200 = DtoResponse & {
  data?: HandlerAuditLogResponse[]
}
