/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetFinanceIncomesReceiptStatus =
  (typeof GetFinanceIncomesReceiptStatus)[keyof typeof GetFinanceIncomesReceiptStatus]

export const GetFinanceIncomesReceiptStatus = {
  PENDING: 'PENDING',
  RECEIVED: 'RECEIVED',
} as const
