/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetFinanceReceiptsPaymentMethod =
  (typeof GetFinanceReceiptsPaymentMethod)[keyof typeof GetFinanceReceiptsPaymentMethod]

export const GetFinanceReceiptsPaymentMethod = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  WECHAT: 'WECHAT',
  ALIPAY: 'ALIPAY',
  CHECK: 'CHECK',
  BALANCE: 'BALANCE',
  OTHER: 'OTHER',
} as const
