/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetFinanceIncomesSummaryParams = {
  /**
   * From date (YYYY-MM-DD)
   */
  from_date?: string
  /**
   * To date (YYYY-MM-DD)
   */
  to_date?: string
}
