/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerReconciliationReportResponse } from './handlerReconciliationReportResponse'

export type GetFinanceTrialBalanceReconciliationReport200 = DtoResponse & {
  data?: HandlerReconciliationReportResponse
}
