/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetInventoryItemsIdTransactionsOrderDir =
  (typeof GetInventoryItemsIdTransactionsOrderDir)[keyof typeof GetInventoryItemsIdTransactionsOrderDir]

export const GetInventoryItemsIdTransactionsOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
