/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerPermissionListResponse } from './handlerPermissionListResponse'

export type GetIdentityPermissions200 = DtoResponse & {
  data?: HandlerPermissionListResponse
}
