/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { GetInventoryItemsIdTransactionsOrderDir } from './getInventoryItemsIdTransactionsOrderDir'
import type { GetInventoryItemsIdTransactionsTransactionType } from './getInventoryItemsIdTransactionsTransactionType'

export type GetInventoryItemsIdTransactionsParams = {
  /**
   * Filter by transaction type
   */
  transaction_type?: GetInventoryItemsIdTransactionsTransactionType
  /**
   * Filter by start date
   */
  start_date?: string
  /**
   * Filter by end date
   */
  end_date?: string
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   * @maximum 100
   */
  page_size?: number
  /**
   * Order by field
   */
  order_by?: string
  /**
   * Order direction
   */
  order_dir?: GetInventoryItemsIdTransactionsOrderDir
}
