/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'

export type GetIdentityTenantsStatsCount200 = DtoResponse & {
  data?: {
    count?: number
  }
}
