/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerUserListResponse } from './handlerUserListResponse'

export type GetIdentityUsers200 = DtoResponse & {
  data?: HandlerUserListResponse
}
