/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetInventoryItemsLookupParams = {
  /**
   * Warehouse ID
   */
  warehouse_id: string
  /**
   * Product ID
   */
  product_id: string
}
