/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoMeta } from './dtoMeta'
import type { DtoResponse } from './dtoResponse'
import type { HandlerStockTakingListResponse } from './handlerStockTakingListResponse'

export type GetInventoryStockTakings200 = DtoResponse & {
  data?: HandlerStockTakingListResponse[]
  meta?: DtoMeta
}
