/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerTenantStatsResponse } from './handlerTenantStatsResponse'

export type GetIdentityTenantsStats200 = DtoResponse & {
  data?: HandlerTenantStatsResponse
}
