/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { Error } from './error'

export type GetPartnerBalanceTransactionsId404 = Error & {
  data?: unknown
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
