/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetPartnerCustomersCustomerIdBalanceTransactionsSourceType =
  (typeof GetPartnerCustomersCustomerIdBalanceTransactionsSourceType)[keyof typeof GetPartnerCustomersCustomerIdBalanceTransactionsSourceType]

export const GetPartnerCustomersCustomerIdBalanceTransactionsSourceType = {
  MANUAL: 'MANUAL',
  SALES_ORDER: 'SALES_ORDER',
  SALES_RETURN: 'SALES_RETURN',
  RECEIPT_VOUCHER: 'RECEIPT_VOUCHER',
  SYSTEM: 'SYSTEM',
} as const
