/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { GetPrintTemplatesOrderDir } from './getPrintTemplatesOrderDir'

export type GetPrintTemplatesParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   */
  page_size?: number
  /**
   * Order by field
   */
  order_by?: string
  /**
   * Order direction
   */
  order_dir?: GetPrintTemplatesOrderDir
  /**
   * Search term
   */
  search?: string
  /**
   * Filter by document type
   */
  doc_type?: string
  /**
   * Filter by status
   */
  status?: string
}
