/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetProductByCategoryOrderDir =
  (typeof GetProductByCategoryOrderDir)[keyof typeof GetProductByCategoryOrderDir]

export const GetProductByCategoryOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
