/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { GetPartnerCustomersIdBalanceTransactionsSourceType } from './getPartnerCustomersIdBalanceTransactionsSourceType'
import type { GetPartnerCustomersIdBalanceTransactionsTransactionType } from './getPartnerCustomersIdBalanceTransactionsTransactionType'

export type GetPartnerCustomersIdBalanceTransactionsParams = {
  /**
   * Transaction type
   */
  transaction_type?: GetPartnerCustomersIdBalanceTransactionsTransactionType
  /**
   * Source type
   */
  source_type?: GetPartnerCustomersIdBalanceTransactionsSourceType
  /**
   * Start date (YYYY-MM-DD)
   */
  date_from?: string
  /**
   * End date (YYYY-MM-DD)
   */
  date_to?: string
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   * @maximum 100
   */
  page_size?: number
}
