/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetPartnerWarehousesOrderDir =
  (typeof GetPartnerWarehousesOrderDir)[keyof typeof GetPartnerWarehousesOrderDir]

export const GetPartnerWarehousesOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
