/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerDailySalesTrendResponse } from './handlerDailySalesTrendResponse'

export type GetReportsSalesDailyTrend200 = DtoResponse & {
  data?: HandlerDailySalesTrendResponse[]
}
