/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerCashFlowItemResponse } from './handlerCashFlowItemResponse'

export type GetReportsFinanceCashFlowItems200 = DtoResponse & {
  data?: HandlerCashFlowItemResponse[]
}
