/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerProfitLossStatementResponse } from './handlerProfitLossStatementResponse'

export type GetReportsFinanceProfitLoss200 = DtoResponse & {
  data?: HandlerProfitLossStatementResponse
}
