/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerPingResponse } from './handlerPingResponse'

export type GetSystemPing200 = DtoResponse & {
  data?: HandlerPingResponse
}
