/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerPurchaseOrderItemResponse } from './handlerPurchaseOrderItemResponse'

export type GetTradePurchaseOrdersIdReceivableItems200 = DtoResponse & {
  data?: HandlerPurchaseOrderItemResponse[]
}
