/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoResponse } from './dtoResponse'

export type GetTradePurchaseOrdersStatsSummary401 = DtoResponse & {
  error?: DtoErrorInfo
}
