/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type GetTradeSalesOrdersStatus =
  (typeof GetTradeSalesOrdersStatus)[keyof typeof GetTradeSalesOrdersStatus]

export const GetTradeSalesOrdersStatus = {
  draft: 'draft',
  confirmed: 'confirmed',
  shipped: 'shipped',
  completed: 'completed',
  cancelled: 'cancelled',
} as const
