/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerDiscrepancyResponse } from './handlerDiscrepancyResponse'

/**
 * Trial balance check response
 */
export interface HandlerTrialBalanceResponse {
  checked_at?: string
  checked_by?: string
  credit_memo_count?: number
  critical_count?: number
  debit_memo_count?: number
  discrepancies?: HandlerDiscrepancyResponse[]
  discrepancy_count?: number
  execution_duration_ms?: number
  id?: string
  net_balance?: number
  notes?: string
  payable_count?: number
  payment_count?: number
  period_end?: string
  period_start?: string
  receipt_count?: number
  receivable_count?: number
  status?: string
  tenant_id?: string
  total_credit_memos?: number
  total_credits?: number
  total_debit_memos?: number
  total_debits?: number
  total_payables?: number
  total_payments?: number
  total_receipts?: number
  total_receivables?: number
  warning_count?: number
}
