/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for cancelling a purchase order
 */
export interface HandlerCancelPurchaseOrderRequest {
  /**
   * @minLength 1
   * @maxLength 500
   */
  reason: string
}
