/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Update other income record request
 */
export interface HandlerUpdateOtherIncomeRecordRequest {
  amount: number
  attachment_urls?: string
  category: string
  description: string
  /** @Description Timestamp when the income was received in ISO 8601 format
@Example 2026-01-15T00:00:00Z */
  received_at: string
  remark?: string
}
