/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCustomerImportRequestConflictMode } from './handlerCustomerImportRequestConflictMode'

export interface HandlerCustomerImportRequest {
  conflict_mode: HandlerCustomerImportRequestConflictMode
  validation_id: string
}
