/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerProductImportResponse } from './handlerProductImportResponse'

export interface HandlerAPIResponseHandlerProductImportResponse {
  data?: HandlerProductImportResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
