/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Update expense record request
 */
export interface HandlerUpdateExpenseRecordRequest {
  amount: number
  attachment_urls?: string
  category: string
  description: string
  incurred_at: string
  remark?: string
}
