/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerSalesSummaryResponse } from './handlerSalesSummaryResponse'

export interface HandlerAPIResponseHandlerSalesSummaryResponse {
  data?: HandlerSalesSummaryResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
