/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Payable payment record response
 */
export interface HandlerPayablePaymentRecordResponse {
  amount?: number
  applied_at?: string
  id?: string
  payment_voucher_id?: string
  remark?: string
}
