/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Cash flow item response
 */
export interface HandlerExpenseIncomeCashFlowItem {
  amount?: number
  category?: string
  /** @Description Date of the cash flow transaction in ISO 8601 format
@Example 2026-01-15T00:00:00Z */
  date?: string
  description?: string
  direction?: string
  id?: string
  number?: string
  type?: string
}
