/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerPurchaseOrderResponse } from './handlerPurchaseOrderResponse'
import type { HandlerReceivedItemResponse } from './handlerReceivedItemResponse'

/**
 * Receive operation result response
 */
export interface HandlerReceiveResultResponse {
  is_fully_received?: boolean
  order?: HandlerPurchaseOrderResponse
  received_items?: HandlerReceivedItemResponse[]
}
