/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerSubscriptionHistoryListResponse } from './handlerSubscriptionHistoryListResponse'

export interface HandlerAPIResponseHandlerSubscriptionHistoryListResponse {
  data?: HandlerSubscriptionHistoryListResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
