/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type HandlerUpdateTenantConfigRequestCostStrategy =
  (typeof HandlerUpdateTenantConfigRequestCostStrategy)[keyof typeof HandlerUpdateTenantConfigRequestCostStrategy]

export const HandlerUpdateTenantConfigRequestCostStrategy = {
  fifo: 'fifo',
  weighted_average: 'weighted_average',
} as const
