/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerCurrentUserResponse } from './handlerCurrentUserResponse'

export interface HandlerAPIResponseHandlerCurrentUserResponse {
  data?: HandlerCurrentUserResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
