/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerAdminAuditLogResponse } from './handlerAdminAuditLogResponse'

/**
 * Paginated list of admin audit logs with metadata
 */
export interface HandlerAdminAuditLogListResponse {
  logs?: HandlerAdminAuditLogResponse[]
  page?: number
  page_size?: number
  total?: number
  total_pages?: number
}
