/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { CsvimportRowError } from './csvimportRowError'
import type { HandlerValidationResponsePreviewItem } from './handlerValidationResponsePreviewItem'

/**
 * Response from CSV import validation
 */
export interface HandlerValidationResponse {
  error_rows?: number
  errors?: CsvimportRowError[]
  is_truncated?: boolean
  preview?: HandlerValidationResponsePreviewItem[]
  total_errors?: number
  total_rows?: number
  valid_rows?: number
  validation_id?: string
}
