/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Order status summary response
 */
export interface HandlerOrderStatusSummaryResponse {
  cancelled?: number
  completed?: number
  confirmed?: number
  draft?: number
  shipped?: number
  total?: number
}
