/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerMessageResponse } from './handlerMessageResponse'

export interface HandlerAPIResponseHandlerMessageResponse {
  data?: HandlerMessageResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
