/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerMarginsRequest } from './handlerMarginsRequest'

/**
 * Request body for updating a print template
 */
export interface HandlerUpdateTemplateRequest {
  content?: string
  /** @maxLength 500 */
  description?: string
  margins?: HandlerMarginsRequest
  /**
   * @minLength 1
   * @maxLength 100
   */
  name?: string
  orientation?: string
  paper_size?: string
}
