/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export interface HandlerCustomerCountByStatusResponse {
  active?: number
  inactive?: number
  suspended?: number
  total?: number
}
