/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for rejecting a return
 */
export interface HandlerRejectReturnRequest {
  /**
   * @minLength 1
   * @maxLength 500
   */
  reason: string
}
