/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export interface HandlerUserResponse {
  avatar?: string
  created_at?: string
  display_name?: string
  email?: string
  id?: string
  last_login_at?: string
  phone?: string
  role_ids?: string[]
  status?: string
  tenant_id?: string
  updated_at?: string
  username?: string
}
