/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for creating a receipt voucher
 */
export interface HandlerCreateReceiptVoucherRequest {
  amount: number
  customer_id: string
  /**
   * @minLength 1
   * @maxLength 200
   */
  customer_name: string
  payment_method: string
  payment_reference?: string
  receipt_date: string
  remark?: string
}
