/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request for refreshing all report caches
 */
export interface HandlerRefreshAllReportsRequest {
  end_date: string
  start_date: string
}
