/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerSubscriptionPlanResponse } from './handlerSubscriptionPlanResponse'

export interface HandlerAPIResponseArrayHandlerSubscriptionPlanResponse {
  data?: HandlerSubscriptionPlanResponse[]
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
