/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoEvaluationContextDTO } from './dtoEvaluationContextDTO'

/**
 * Request body for getting client configuration
 */
export interface HandlerClientConfigHTTPRequest {
  context?: DtoEvaluationContextDTO
}
