/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Return status summary response
 */
export interface HandlerPurchaseReturnStatusSummaryResponse {
  approved?: number
  cancelled?: number
  completed?: number
  draft?: number
  pending?: number
  pending_approval?: number
  pending_shipment?: number
  rejected?: number
  shipped?: number
  total?: number
}
