/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Return item for creation
 */
export interface HandlerCreatePurchaseReturnItemInput {
  batch_number?: string
  condition_on_return?: string
  purchase_order_item_id: string
  reason?: string
  return_quantity: number
}
