/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerAdminCreateTenantRequestPlan } from './handlerAdminCreateTenantRequestPlan'

/**
 * Request body for creating a new tenant in the platform
 */
export interface HandlerAdminCreateTenantRequest {
  /** @maxLength 500 */
  address?: string
  /**
   * @minLength 2
   * @maxLength 50
   */
  code: string
  /** @maxLength 200 */
  contact_email?: string
  /** @maxLength 100 */
  contact_name?: string
  /** @maxLength 20 */
  contact_phone?: string
  /**
   * @minLength 2
   * @maxLength 200
   */
  name: string
  /** @maxLength 1000 */
  notes?: string
  plan?: HandlerAdminCreateTenantRequestPlan
  /** @maxLength 50 */
  short_name?: string
  /**
   * @minimum 0
   * @maximum 90
   */
  trial_days?: number
}
