/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Detailed profit and loss statement
 */
export interface HandlerProfitLossStatementResponse {
  cost_of_goods_sold?: number
  gross_profit?: number
  gross_profit_margin?: number
  net_profit?: number
  net_profit_margin?: number
  operating_expenses?: number
  other_expenses?: number
  other_income?: number
  period_end?: string
  period_start?: string
  revenue?: number
}
