/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerAdminTenantListResponse } from './handlerAdminTenantListResponse'

export interface HandlerAPIResponseHandlerAdminTenantListResponse {
  data?: HandlerAdminTenantListResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
