/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Mark income received request
 */
export interface HandlerMarkIncomeReceivedRequest {
  payment_method: string
}
