/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for cancelling a stock taking
 */
export interface HandlerCancelStockTakingRequest {
  /** @maxLength 500 */
  reason?: string
}
