/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Monthly profit trend data point
 */
export interface HandlerMonthlyProfitTrendResponse {
  cost?: number
  expenses?: number
  gross_profit?: number
  month?: string
  net_profit?: number
  profit_margin?: number
  revenue?: number
}
