/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerReconciliationReportResponse } from './handlerReconciliationReportResponse'

export interface HandlerAPIResponseHandlerReconciliationReportResponse {
  data?: HandlerReconciliationReportResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
