/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export interface HandlerOutboxEntryResponse {
  aggregate_id?: string
  aggregate_type?: string
  created_at?: string
  event_id?: string
  event_type?: string
  id?: string
  last_error?: string
  max_retries?: number
  next_retry_at?: string
  processed_at?: string
  retry_count?: number
  status?: string
  tenant_id?: string
  updated_at?: string
}
