/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerWarehouseCountByStatusResponse } from './handlerWarehouseCountByStatusResponse'

export interface HandlerAPIResponseHandlerWarehouseCountByStatusResponse {
  data?: HandlerWarehouseCountByStatusResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
