/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerManualAllocationInputRequest } from './handlerManualAllocationInputRequest'

/**
 * Request body for reconciling a voucher
 */
export interface HandlerReconcileRequest {
  manual_allocations?: HandlerManualAllocationInputRequest[]
  strategy_type: string
}
