/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerChangePlanRequestPlan } from './handlerChangePlanRequestPlan'

/**
 * Request body for changing tenant subscription plan
 */
export interface HandlerChangePlanRequest {
  plan: HandlerChangePlanRequestPlan
  reason?: string
}
