/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerStrategyInfo } from './handlerStrategyInfo'

export interface HandlerAPIResponseArrayHandlerStrategyInfo {
  data?: HandlerStrategyInfo[]
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
