/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerInventoryImportRequestConflictMode } from './handlerInventoryImportRequestConflictMode'

export interface HandlerInventoryImportRequest {
  conflict_mode: HandlerInventoryImportRequestConflictMode
  validation_id: string
}
