/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Daily sales trend data point
 */
export interface HandlerDailySalesTrendResponse {
  date?: string
  items_sold?: number
  order_count?: number
  total_amount?: number
  total_profit?: number
}
