/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerConvertUnitResponse } from './handlerConvertUnitResponse'

export interface HandlerAPIResponseHandlerConvertUnitResponse {
  data?: HandlerConvertUnitResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
