/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerCustomerListResponse } from './handlerCustomerListResponse'

export interface HandlerAPIResponseArrayHandlerCustomerListResponse {
  data?: HandlerCustomerListResponse[]
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
