/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Tenant configuration including quotas and regional settings
 */
export interface HandlerAdminTenantConfigResponse {
  cost_strategy?: string
  currency?: string
  locale?: string
  max_products?: number
  max_users?: number
  max_warehouses?: number
  timezone?: string
}
