/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Profit breakdown by product
 */
export interface HandlerProfitByProductResponse {
  category_name?: string
  cost?: number
  gross_profit?: number
  product_id?: string
  product_name?: string
  profit_margin?: number
  quantity?: number
  revenue?: number
}
