/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for consuming locked stock (shipment/fulfillment)
 */
export interface HandlerDeductStockRequest {
  lock_id: string
  operator_id?: string
  reference?: string
  source_id: string
  source_type: string
}
