/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Sales return item response
 */
export interface HandlerSalesReturnItemResponse {
  condition_on_return?: string
  created_at?: string
  id?: string
  original_quantity?: number
  product_code?: string
  product_id?: string
  product_name?: string
  reason?: string
  refund_amount?: number
  return_quantity?: number
  sales_order_item_id?: string
  unit?: string
  unit_price?: number
  updated_at?: string
}
