/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerInventoryItemResponse } from './handlerInventoryItemResponse'

export interface HandlerAPIResponseHandlerInventoryItemResponse {
  data?: HandlerInventoryItemResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
