/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for confirming a purchase order
 */
export interface HandlerConfirmPurchaseOrderRequest {
  warehouse_id?: string
}
