/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerInventoryValueByWarehouseResponse } from './handlerInventoryValueByWarehouseResponse'

export interface HandlerAPIResponseArrayHandlerInventoryValueByWarehouseResponse {
  data?: HandlerInventoryValueByWarehouseResponse[]
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
