/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for updating a sales order (draft only)
 */
export interface HandlerUpdateSalesOrderRequest {
  discount?: number
  remark?: string
  warehouse_id?: string
}
