/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerTrialBalanceResponse } from './handlerTrialBalanceResponse'

export interface HandlerAPIResponseHandlerTrialBalanceResponse {
  data?: HandlerTrialBalanceResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
