/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export interface HandlerRoleResponse {
  code?: string
  created_at?: string
  description?: string
  id?: string
  is_enabled?: boolean
  is_system_role?: boolean
  name?: string
  permissions?: string[]
  sort_order?: number
  tenant_id?: string
  updated_at?: string
  user_count?: number
}
