/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Cash flow statement
 */
export interface HandlerCashFlowStatementResponse {
  cash_from_sales?: number
  cash_to_expenses?: number
  cash_to_purchases?: number
  closing_cash_balance?: number
  net_cash_flow?: number
  opening_cash_balance?: number
  other_cash_inflow?: number
  other_cash_outflow?: number
  period_end?: string
  period_start?: string
}
