/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for approving a stock taking
 */
export interface HandlerApproveStockTakingRequest {
  approver_id: string
  approver_name: string
  note?: string
}
