/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerProductUnitResponse } from './handlerProductUnitResponse'

export interface HandlerAPIResponseArrayHandlerProductUnitResponse {
  data?: HandlerProductUnitResponse[]
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
