/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoGetClientConfigResponse } from './dtoGetClientConfigResponse'
import type { DtoMeta } from './dtoMeta'

export interface HandlerAPIResponseDtoGetClientConfigResponse {
  data?: DtoGetClientConfigResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
