/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerPermissionListResponse } from './handlerPermissionListResponse'

export interface HandlerAPIResponseHandlerPermissionListResponse {
  data?: HandlerPermissionListResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
