/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerCategoryResponse } from './handlerCategoryResponse'

export interface HandlerAPIResponseHandlerCategoryResponse {
  data?: HandlerCategoryResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
