/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { DtoOverrideListResponse } from './dtoOverrideListResponse'

export interface HandlerAPIResponseDtoOverrideListResponse {
  data?: DtoOverrideListResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
