/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Customer level details
 */
export interface HandlerCustomerLevelResponse {
  code?: string
  created_at?: string
  customer_count?: number
  description?: string
  discount_percent?: number
  discount_rate?: number
  id?: string
  is_active?: boolean
  is_default?: boolean
  name?: string
  sort_order?: number
  tenant_id?: string
  updated_at?: string
}
