/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerMarginsResponse } from './handlerMarginsResponse'

/**
 * Rendered template response
 */
export interface HandlerRenderTemplateHTTPResponse {
  html?: string
  margins?: HandlerMarginsResponse
  orientation?: string
  paper_size?: string
  template_id?: string
}
