/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for updating an auto print rule
 */
export interface HandlerUpdateAutoPrintRuleHTTPRequest {
  auto_print?: boolean
  /**
   * @minimum 1
   * @maximum 100
   */
  copies?: number
  printer_name?: string
  template_id?: string
}
