/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for updating a return item
 */
export interface HandlerUpdatePurchaseReturnItemRequest {
  batch_number?: string
  condition_on_return?: string
  reason?: string
  return_quantity?: number
}
