/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Manual allocation input for reconciliation
 */
export interface HandlerManualAllocationInputRequest {
  amount: number
  target_id: string
}
