/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export interface HandlerResetPasswordRequest {
  /**
   * @minLength 8
   * @maxLength 128
   */
  new_password: string
}
