/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type HandlerCreateSupplierRequestType =
  (typeof HandlerCreateSupplierRequestType)[keyof typeof HandlerCreateSupplierRequestType]

export const HandlerCreateSupplierRequestType = {
  manufacturer: 'manufacturer',
  distributor: 'distributor',
  retailer: 'retailer',
  service: 'service',
} as const
