/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Request body for checking if a quantity is available
 */
export interface HandlerCheckAvailabilityRequest {
  product_id: string
  quantity: number
  warehouse_id: string
}
