/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMessageResponse } from './dtoMessageResponse'
import type { DtoMeta } from './dtoMeta'

export interface HandlerAPIResponseDtoMessageResponse {
  data?: DtoMessageResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
