/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerReceivableAllocationResponse } from './handlerReceivableAllocationResponse'

/**
 * Receipt voucher response
 */
export interface HandlerReceiptVoucherResponse {
  allocated_amount?: number
  allocations?: HandlerReceivableAllocationResponse[]
  amount?: number
  confirmed_at?: string
  created_at?: string
  customer_id?: string
  customer_name?: string
  id?: string
  payment_method?: string
  payment_reference?: string
  receipt_date?: string
  remark?: string
  status?: string
  tenant_id?: string
  unallocated_amount?: number
  updated_at?: string
  version?: number
  voucher_number?: string
}
