/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerTemplateResponse } from './handlerTemplateResponse'

export interface HandlerAPIResponseArrayHandlerTemplateResponse {
  data?: HandlerTemplateResponse[]
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
