/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Payment record response
 */
export interface HandlerPaymentRecordResponse {
  amount?: number
  applied_at?: string
  id?: string
  receipt_voucher_id?: string
  remark?: string
}
