/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Update other income record request
 */
export interface HandlerUpdateOtherIncomeRecordRequest {
  amount: number
  attachment_urls?: string
  category: string
  description: string
  received_at: string
  remark?: string
}
