/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerOtherIncomeRecordResponse } from './handlerOtherIncomeRecordResponse'

export interface HandlerAPIResponseHandlerOtherIncomeRecordResponse {
  data?: HandlerOtherIncomeRecordResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
