/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoErrorInfo } from './dtoErrorInfo'
import type { DtoMeta } from './dtoMeta'
import type { HandlerReconcileReceiptResultResponse } from './handlerReconcileReceiptResultResponse'

export interface HandlerAPIResponseHandlerReconcileReceiptResultResponse {
  data?: HandlerReconcileReceiptResultResponse
  error?: DtoErrorInfo
  meta?: DtoMeta
  success?: boolean
}
