/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

/**
 * Expense record response
 */
export interface HandlerExpenseRecordResponse {
  amount?: number
  approval_remark?: string
  approved_at?: string
  approved_by?: string
  attachment_urls?: string
  category?: string
  category_name?: string
  created_at?: string
  description?: string
  expense_number?: string
  id?: string
  incurred_at?: string
  paid_at?: string
  payment_method?: string
  payment_status?: string
  rejected_at?: string
  rejected_by?: string
  rejection_reason?: string
  remark?: string
  status?: string
  submitted_at?: string
  submitted_by?: string
  tenant_id?: string
  updated_at?: string
  version?: number
}
