/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { CsvimportRowError } from './csvimportRowError'
import type { HandlerSupplierValidationResponsePreviewItem } from './handlerSupplierValidationResponsePreviewItem'

/**
 * Response from supplier CSV validation
 */
export interface HandlerSupplierValidationResponse {
  error_rows?: number
  errors?: CsvimportRowError[]
  is_truncated?: boolean
  preview?: HandlerSupplierValidationResponsePreviewItem[]
  total_errors?: number
  total_rows?: number
  valid_rows?: number
  validation_id?: string
  warnings?: string[]
}
