/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListInventoryTransactionsByItemTransactionType =
  (typeof ListInventoryTransactionsByItemTransactionType)[keyof typeof ListInventoryTransactionsByItemTransactionType]

export const ListInventoryTransactionsByItemTransactionType = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
  LOCK: 'LOCK',
  UNLOCK: 'UNLOCK',
  ADJUSTMENT: 'ADJUSTMENT',
} as const
