/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { ListSuppliersOrderDir } from './listSuppliersOrderDir'
import type { ListSuppliersStatus } from './listSuppliersStatus'
import type { ListSuppliersType } from './listSuppliersType'

export type ListSuppliersParams = {
  /**
   * Search term (name, code, phone, email)
   */
  search?: string
  /**
   * Supplier status
   */
  status?: ListSuppliersStatus
  /**
   * Supplier type
   */
  type?: ListSuppliersType
  /**
   * City
   */
  city?: string
  /**
   * Province
   */
  province?: string
  /**
   * Minimum rating (0-5)
   */
  min_rating?: number
  /**
   * Maximum rating (0-5)
   */
  max_rating?: number
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   * @maximum 100
   */
  page_size?: number
  /**
   * Order by field
   */
  order_by?: string
  /**
   * Order direction
   */
  order_dir?: ListSuppliersOrderDir
}
