/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListInventoryTransactionsByItemOrderDir =
  (typeof ListInventoryTransactionsByItemOrderDir)[keyof typeof ListInventoryTransactionsByItemOrderDir]

export const ListInventoryTransactionsByItemOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
