/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListWarehousesType = (typeof ListWarehousesType)[keyof typeof ListWarehousesType]

export const ListWarehousesType = {
  physical: 'physical',
  virtual: 'virtual',
  consign: 'consign',
  transit: 'transit',
} as const
