/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListPurchaseOrdersStatus =
  (typeof ListPurchaseOrdersStatus)[keyof typeof ListPurchaseOrdersStatus]

export const ListPurchaseOrdersStatus = {
  draft: 'draft',
  confirmed: 'confirmed',
  partial_received: 'partial_received',
  completed: 'completed',
  cancelled: 'cancelled',
} as const
