/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListSalesReturnsStatus =
  (typeof ListSalesReturnsStatus)[keyof typeof ListSalesReturnsStatus]

export const ListSalesReturnsStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const
