/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListProductAttachmentsOrderDir =
  (typeof ListProductAttachmentsOrderDir)[keyof typeof ListProductAttachmentsOrderDir]

export const ListProductAttachmentsOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
