/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListInventoryByWarehouseOrderDir =
  (typeof ListInventoryByWarehouseOrderDir)[keyof typeof ListInventoryByWarehouseOrderDir]

export const ListInventoryByWarehouseOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
