/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListPrintTemplateTemplatesOrderDir =
  (typeof ListPrintTemplateTemplatesOrderDir)[keyof typeof ListPrintTemplateTemplatesOrderDir]

export const ListPrintTemplateTemplatesOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
