/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListSalesOrdersOrderDir =
  (typeof ListSalesOrdersOrderDir)[keyof typeof ListSalesOrdersOrderDir]

export const ListSalesOrdersOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
