/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListInventoryTransactionsTransactionType =
  (typeof ListInventoryTransactionsTransactionType)[keyof typeof ListInventoryTransactionsTransactionType]

export const ListInventoryTransactionsTransactionType = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
  LOCK: 'LOCK',
  UNLOCK: 'UNLOCK',
  ADJUSTMENT: 'ADJUSTMENT',
} as const
