/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListProductAttachmentsType =
  (typeof ListProductAttachmentsType)[keyof typeof ListProductAttachmentsType]

export const ListProductAttachmentsType = {
  main_image: 'main_image',
  gallery_image: 'gallery_image',
  document: 'document',
  other: 'other',
} as const
