/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { ListProductsOrderDir } from './listProductsOrderDir'
import type { ListProductsStatus } from './listProductsStatus'

export type ListProductsParams = {
  /**
   * Search term (name, code, barcode)
   */
  search?: string
  /**
   * Product status
   */
  status?: ListProductsStatus
  /**
   * Category ID
   */
  category_id?: string
  /**
   * Unit of measure
   */
  unit?: string
  /**
   * Minimum selling price
   */
  min_price?: number
  /**
   * Maximum selling price
   */
  max_price?: number
  /**
   * Filter by barcode presence
   */
  has_barcode?: boolean
  /**
   * Page number
   */
  page?: number
  /**
   * Page size
   * @maximum 100
   */
  page_size?: number
  /**
   * Order by field
   */
  order_by?: string
  /**
   * Order direction
   */
  order_dir?: ListProductsOrderDir
}
