/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListCategoriesStatus = (typeof ListCategoriesStatus)[keyof typeof ListCategoriesStatus]

export const ListCategoriesStatus = {
  active: 'active',
  inactive: 'inactive',
} as const
