/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */

export type ListCustomersOrderDir =
  (typeof ListCustomersOrderDir)[keyof typeof ListCustomersOrderDir]

export const ListCustomersOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const
