/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerLoginRequest } from './handlerLoginRequest'

export type LoginAuthBody = { [key: string]: unknown } | HandlerLoginRequest
