/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerConfirmPurchaseOrderRequest } from './handlerConfirmPurchaseOrderRequest'

export type PostTradePurchaseOrdersIdConfirmBody =
  | { [key: string]: unknown }
  | HandlerConfirmPurchaseOrderRequest
