/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerOutboxEntryResponse } from './handlerOutboxEntryResponse'

export type PostSystemOutboxIdRetry200 = DtoResponse & {
  data?: HandlerOutboxEntryResponse
}
