/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCancelReturnRequest } from './handlerCancelReturnRequest'

export type PostTradeSalesReturnsIdCancelBody =
  | { [key: string]: unknown }
  | HandlerCancelReturnRequest
