/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerBalanceTransactionResponse } from './handlerBalanceTransactionResponse'

export type PostPartnerCustomersCustomerIdBalanceAdjust201 = DtoResponse & {
  data?: HandlerBalanceTransactionResponse
}
