/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerResetPasswordRequest } from './handlerResetPasswordRequest'

export type PostIdentityUsersIdResetPasswordBody =
  | { [key: string]: unknown }
  | HandlerResetPasswordRequest
