/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCancelPurchaseOrderRequest } from './handlerCancelPurchaseOrderRequest'

export type PostTradePurchaseOrdersIdCancelBody =
  | { [key: string]: unknown }
  | HandlerCancelPurchaseOrderRequest
