/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerReceivePurchaseOrderRequest } from './handlerReceivePurchaseOrderRequest'

export type PostTradePurchaseOrdersIdReceiveBody =
  | { [key: string]: unknown }
  | HandlerReceivePurchaseOrderRequest
