/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerStockTakingResponse } from './handlerStockTakingResponse'

export type PostInventoryStockTakingsIdCounts200 = DtoResponse & {
  data?: HandlerStockTakingResponse
}
