/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerRechargeRequest } from './handlerRechargeRequest'

export type PostPartnerCustomersIdBalanceRechargeBody =
  | { [key: string]: unknown }
  | HandlerRechargeRequest
