/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCreateOverrideHTTPRequest } from './handlerCreateOverrideHTTPRequest'

export type PostFeatureFlagsKeyOverridesBody =
  | { [key: string]: unknown }
  | HandlerCreateOverrideHTTPRequest
