/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerLockUserRequest } from './handlerLockUserRequest'

export type PostIdentityUsersIdLockBody = { [key: string]: unknown } | HandlerLockUserRequest
