/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerReconcileRequest } from './handlerReconcileRequest'

export type PostFinancePaymentsIdReconcileBody =
  | { [key: string]: unknown }
  | HandlerReconcileRequest
