/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCreateSalesReturnRequest } from './handlerCreateSalesReturnRequest'

export type PostTradeSalesReturnsBody = { [key: string]: unknown } | HandlerCreateSalesReturnRequest
