/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerOtherIncomeRecordResponse } from './handlerOtherIncomeRecordResponse'

export type PostFinanceIncomesIdConfirm200 = DtoResponse & {
  data?: HandlerOtherIncomeRecordResponse
}
