/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerCreatePaymentVoucherRequest } from './handlerCreatePaymentVoucherRequest'

export type PostFinancePaymentsBody =
  | { [key: string]: unknown }
  | HandlerCreatePaymentVoucherRequest
