/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerForceLogoutRequest } from './handlerForceLogoutRequest'

export type PostAuthForceLogoutBody = { [key: string]: unknown } | HandlerForceLogoutRequest
