/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerTenantResponse } from './handlerTenantResponse'

export type PutIdentityTenantsId200 = DtoResponse & {
  data?: HandlerTenantResponse
}
