/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdateCustomerLevelRequest } from './handlerUpdateCustomerLevelRequest'

export type PutPartnerCustomerLevelsIdBody =
  | { [key: string]: unknown }
  | HandlerUpdateCustomerLevelRequest
