/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerSetPaymentTermsRequest } from './handlerSetPaymentTermsRequest'

export type PutPartnerSuppliersIdPaymentTermsBody =
  | { [key: string]: unknown }
  | HandlerSetPaymentTermsRequest
