/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerSupplierResponse } from './handlerSupplierResponse'

export type PutPartnerSuppliersId200 = DtoResponse & {
  data?: HandlerSupplierResponse
}
