/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { DtoResponse } from './dtoResponse'
import type { HandlerSalesReturnResponse } from './handlerSalesReturnResponse'

export type PutTradeSalesReturnsIdItemsItemId200 = DtoResponse & {
  data?: HandlerSalesReturnResponse
}
