/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerRefreshReportRequest } from './handlerRefreshReportRequest'

export type RefreshReportReportBody = { [key: string]: unknown } | HandlerRefreshReportRequest
