/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerRejectStockTakingRequest } from './handlerRejectStockTakingRequest'

export type RejectStockTakingBody = { [key: string]: unknown } | HandlerRejectStockTakingRequest
