/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerRejectReturnRequest } from './handlerRejectReturnRequest'

export type RejectSalesReturnBody = { [key: string]: unknown } | HandlerRejectReturnRequest
