/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerSetTenantPlanRequest } from './handlerSetTenantPlanRequest'

export type SetPlanTenantBody = { [key: string]: unknown } | HandlerSetTenantPlanRequest
