/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdateCustomerCodeRequest } from './handlerUpdateCustomerCodeRequest'

export type UpdateCustomerCodeBody = { [key: string]: unknown } | HandlerUpdateCustomerCodeRequest
