/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdateSupplierRequest } from './handlerUpdateSupplierRequest'

export type UpdateSupplierBody = { [key: string]: unknown } | HandlerUpdateSupplierRequest
