/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdateTenantConfigRequest } from './handlerUpdateTenantConfigRequest'

export type UpdateTenantConfigBody = { [key: string]: unknown } | HandlerUpdateTenantConfigRequest
