/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdateSalesOrderRequest } from './handlerUpdateSalesOrderRequest'

export type UpdateSalesOrderBody = { [key: string]: unknown } | HandlerUpdateSalesOrderRequest
