/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdatePurchaseReturnRequest } from './handlerUpdatePurchaseReturnRequest'

export type UpdatePurchaseReturnBody =
  | { [key: string]: unknown }
  | HandlerUpdatePurchaseReturnRequest
