/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdateOrderItemRequest } from './handlerUpdateOrderItemRequest'

export type UpdateSalesOrderItemBody = { [key: string]: unknown } | HandlerUpdateOrderItemRequest
