/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type { HandlerUpdatePurchaseOrderRequest } from './handlerUpdatePurchaseOrderRequest'

export type UpdatePurchaseOrderBody = { [key: string]: unknown } | HandlerUpdatePurchaseOrderRequest
