/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  GetFinanceTrialBalanceAuditLogs200,
  GetFinanceTrialBalanceAuditLogsBody,
  GetFinanceTrialBalanceAuditLogsParams,
  GetFinanceTrialBalanceQuickCheck200,
  GetFinanceTrialBalanceQuickCheckBody,
  GetFinanceTrialBalanceReconciliationReport200,
  GetFinanceTrialBalanceReconciliationReportBody,
  PostFinanceTrialBalanceCheck200,
  PostFinanceTrialBalanceCheckBody,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getFinanceTrialBalance = () => {
  /**
   * Retrieves the most recent trial balance audit logs
   * @summary Get trial balance audit logs
   */
  const getFinanceTrialBalanceAuditLogs = (
    getFinanceTrialBalanceAuditLogsBody: GetFinanceTrialBalanceAuditLogsBody,
    params?: GetFinanceTrialBalanceAuditLogsParams,
    options?: SecondParameter<typeof customInstance<GetFinanceTrialBalanceAuditLogs200>>
  ) => {
    return customInstance<GetFinanceTrialBalanceAuditLogs200>(
      {
        url: `/finance/trial-balance/audit-logs`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        params,
      },
      options
    )
  }
  /**
   * Performs a comprehensive trial balance check and returns discrepancies
   * @summary Perform trial balance check
   */
  const postFinanceTrialBalanceCheck = (
    postFinanceTrialBalanceCheckBody: PostFinanceTrialBalanceCheckBody,
    options?: SecondParameter<typeof customInstance<PostFinanceTrialBalanceCheck200>>
  ) => {
    return customInstance<PostFinanceTrialBalanceCheck200>(
      {
        url: `/finance/trial-balance/check`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postFinanceTrialBalanceCheckBody,
      },
      options
    )
  }
  /**
   * Performs a quick balance check (minimal validation) for use before operations
   * @summary Quick balance check
   */
  const getFinanceTrialBalanceQuickCheck = (
    getFinanceTrialBalanceQuickCheckBody: GetFinanceTrialBalanceQuickCheckBody,
    options?: SecondParameter<typeof customInstance<GetFinanceTrialBalanceQuickCheck200>>
  ) => {
    return customInstance<GetFinanceTrialBalanceQuickCheck200>(
      {
        url: `/finance/trial-balance/quick-check`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      },
      options
    )
  }
  /**
   * Generates a detailed reconciliation report with health score and recommendations
   * @summary Get reconciliation report
   */
  const getFinanceTrialBalanceReconciliationReport = (
    getFinanceTrialBalanceReconciliationReportBody: GetFinanceTrialBalanceReconciliationReportBody,
    options?: SecondParameter<typeof customInstance<GetFinanceTrialBalanceReconciliationReport200>>
  ) => {
    return customInstance<GetFinanceTrialBalanceReconciliationReport200>(
      {
        url: `/finance/trial-balance/reconciliation-report`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      },
      options
    )
  }
  return {
    getFinanceTrialBalanceAuditLogs,
    postFinanceTrialBalanceCheck,
    getFinanceTrialBalanceQuickCheck,
    getFinanceTrialBalanceReconciliationReport,
  }
}
export type GetFinanceTrialBalanceAuditLogsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFinanceTrialBalance>['getFinanceTrialBalanceAuditLogs']>>
>
export type PostFinanceTrialBalanceCheckResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFinanceTrialBalance>['postFinanceTrialBalanceCheck']>>
>
export type GetFinanceTrialBalanceQuickCheckResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFinanceTrialBalance>['getFinanceTrialBalanceQuickCheck']>>
>
export type GetFinanceTrialBalanceReconciliationReportResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getFinanceTrialBalance>['getFinanceTrialBalanceReconciliationReport']
    >
  >
>
