/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DtoResponse,
  GetCatalogProductsIdUnits200,
  GetCatalogProductsIdUnitsDefaultPurchase200,
  GetCatalogProductsIdUnitsDefaultSales200,
  GetCatalogProductsIdUnitsUnitId200,
  HandlerConvertUnitRequest,
  HandlerCreateProductUnitRequest,
  HandlerUpdateProductUnitRequest,
  PostCatalogProductsIdUnits201,
  PostCatalogProductsIdUnitsConvert200,
  PutCatalogProductsIdUnitsUnitId200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getProductUnits = () => {
  /**
   * List all alternate units for a product
   * @summary List product units
   */
  const getCatalogProductsIdUnits = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetCatalogProductsIdUnits200>>
  ) => {
    return customInstance<GetCatalogProductsIdUnits200>(
      { url: `/catalog/products/${id}/units`, method: 'GET' },
      options
    )
  }
  /**
   * Create a new alternate unit for a product
   * @summary Create a product unit
   */
  const postCatalogProductsIdUnits = (
    id: string,
    handlerCreateProductUnitRequest: HandlerCreateProductUnitRequest,
    options?: SecondParameter<typeof customInstance<PostCatalogProductsIdUnits201>>
  ) => {
    return customInstance<PostCatalogProductsIdUnits201>(
      {
        url: `/catalog/products/${id}/units`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateProductUnitRequest,
      },
      options
    )
  }
  /**
   * Delete a product unit
   * @summary Delete product unit
   */
  const deleteCatalogProductsIdUnitsUnitId = (
    id: string,
    unitId: string,
    options?: SecondParameter<typeof customInstance<DtoResponse>>
  ) => {
    return customInstance<DtoResponse>(
      { url: `/catalog/products/${id}/units/${unitId}`, method: 'DELETE' },
      options
    )
  }
  /**
   * Retrieve a product unit by its ID
   * @summary Get product unit by ID
   */
  const getCatalogProductsIdUnitsUnitId = (
    id: string,
    unitId: string,
    options?: SecondParameter<typeof customInstance<GetCatalogProductsIdUnitsUnitId200>>
  ) => {
    return customInstance<GetCatalogProductsIdUnitsUnitId200>(
      { url: `/catalog/products/${id}/units/${unitId}`, method: 'GET' },
      options
    )
  }
  /**
   * Update an existing product unit
   * @summary Update product unit
   */
  const putCatalogProductsIdUnitsUnitId = (
    id: string,
    unitId: string,
    handlerUpdateProductUnitRequest: HandlerUpdateProductUnitRequest,
    options?: SecondParameter<typeof customInstance<PutCatalogProductsIdUnitsUnitId200>>
  ) => {
    return customInstance<PutCatalogProductsIdUnitsUnitId200>(
      {
        url: `/catalog/products/${id}/units/${unitId}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateProductUnitRequest,
      },
      options
    )
  }
  /**
   * Convert quantity from one unit to another for a product
   * @summary Convert quantity between units
   */
  const postCatalogProductsIdUnitsConvert = (
    id: string,
    handlerConvertUnitRequest: HandlerConvertUnitRequest,
    options?: SecondParameter<typeof customInstance<PostCatalogProductsIdUnitsConvert200>>
  ) => {
    return customInstance<PostCatalogProductsIdUnitsConvert200>(
      {
        url: `/catalog/products/${id}/units/convert`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerConvertUnitRequest,
      },
      options
    )
  }
  /**
   * Get the default purchase unit for a product
   * @summary Get default purchase unit
   */
  const getCatalogProductsIdUnitsDefaultPurchase = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetCatalogProductsIdUnitsDefaultPurchase200>>
  ) => {
    return customInstance<GetCatalogProductsIdUnitsDefaultPurchase200>(
      { url: `/catalog/products/${id}/units/default-purchase`, method: 'GET' },
      options
    )
  }
  /**
   * Get the default sales unit for a product
   * @summary Get default sales unit
   */
  const getCatalogProductsIdUnitsDefaultSales = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetCatalogProductsIdUnitsDefaultSales200>>
  ) => {
    return customInstance<GetCatalogProductsIdUnitsDefaultSales200>(
      { url: `/catalog/products/${id}/units/default-sales`, method: 'GET' },
      options
    )
  }
  return {
    getCatalogProductsIdUnits,
    postCatalogProductsIdUnits,
    deleteCatalogProductsIdUnitsUnitId,
    getCatalogProductsIdUnitsUnitId,
    putCatalogProductsIdUnitsUnitId,
    postCatalogProductsIdUnitsConvert,
    getCatalogProductsIdUnitsDefaultPurchase,
    getCatalogProductsIdUnitsDefaultSales,
  }
}
export type GetCatalogProductsIdUnitsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['getCatalogProductsIdUnits']>>
>
export type PostCatalogProductsIdUnitsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['postCatalogProductsIdUnits']>>
>
export type DeleteCatalogProductsIdUnitsUnitIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['deleteCatalogProductsIdUnitsUnitId']>>
>
export type GetCatalogProductsIdUnitsUnitIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['getCatalogProductsIdUnitsUnitId']>>
>
export type PutCatalogProductsIdUnitsUnitIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['putCatalogProductsIdUnitsUnitId']>>
>
export type PostCatalogProductsIdUnitsConvertResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['postCatalogProductsIdUnitsConvert']>>
>
export type GetCatalogProductsIdUnitsDefaultPurchaseResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProductUnits>['getCatalogProductsIdUnitsDefaultPurchase']>
  >
>
export type GetCatalogProductsIdUnitsDefaultSalesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['getCatalogProductsIdUnitsDefaultSales']>>
>
