/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DtoResponse,
  GetCatalogProductsProductIdUnits200,
  GetCatalogProductsProductIdUnitsDefaultPurchase200,
  GetCatalogProductsProductIdUnitsDefaultSales200,
  GetCatalogProductsProductIdUnitsId200,
  HandlerConvertUnitRequest,
  HandlerCreateProductUnitRequest,
  HandlerUpdateProductUnitRequest,
  PostCatalogProductsProductIdUnits201,
  PostCatalogProductsProductIdUnitsConvert200,
  PutCatalogProductsProductIdUnitsId200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getProductUnits = () => {
  /**
   * List all alternate units for a product
   * @summary List product units
   */
  const getCatalogProductsProductIdUnits = (
    productId: string,
    options?: SecondParameter<typeof customInstance<GetCatalogProductsProductIdUnits200>>
  ) => {
    return customInstance<GetCatalogProductsProductIdUnits200>(
      { url: `/catalog/products/${productId}/units`, method: 'GET' },
      options
    )
  }
  /**
   * Create a new alternate unit for a product
   * @summary Create a product unit
   */
  const postCatalogProductsProductIdUnits = (
    productId: string,
    handlerCreateProductUnitRequest: HandlerCreateProductUnitRequest,
    options?: SecondParameter<typeof customInstance<PostCatalogProductsProductIdUnits201>>
  ) => {
    return customInstance<PostCatalogProductsProductIdUnits201>(
      {
        url: `/catalog/products/${productId}/units`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateProductUnitRequest,
      },
      options
    )
  }
  /**
   * Delete a product unit
   * @summary Delete product unit
   */
  const deleteCatalogProductsProductIdUnitsId = (
    productId: string,
    id: string,
    options?: SecondParameter<typeof customInstance<DtoResponse>>
  ) => {
    return customInstance<DtoResponse>(
      { url: `/catalog/products/${productId}/units/${id}`, method: 'DELETE' },
      options
    )
  }
  /**
   * Retrieve a product unit by its ID
   * @summary Get product unit by ID
   */
  const getCatalogProductsProductIdUnitsId = (
    productId: string,
    id: string,
    options?: SecondParameter<typeof customInstance<GetCatalogProductsProductIdUnitsId200>>
  ) => {
    return customInstance<GetCatalogProductsProductIdUnitsId200>(
      { url: `/catalog/products/${productId}/units/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update an existing product unit
   * @summary Update product unit
   */
  const putCatalogProductsProductIdUnitsId = (
    productId: string,
    id: string,
    handlerUpdateProductUnitRequest: HandlerUpdateProductUnitRequest,
    options?: SecondParameter<typeof customInstance<PutCatalogProductsProductIdUnitsId200>>
  ) => {
    return customInstance<PutCatalogProductsProductIdUnitsId200>(
      {
        url: `/catalog/products/${productId}/units/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateProductUnitRequest,
      },
      options
    )
  }
  /**
   * Convert quantity from one unit to another for a product
   * @summary Convert quantity between units
   */
  const postCatalogProductsProductIdUnitsConvert = (
    productId: string,
    handlerConvertUnitRequest: HandlerConvertUnitRequest,
    options?: SecondParameter<typeof customInstance<PostCatalogProductsProductIdUnitsConvert200>>
  ) => {
    return customInstance<PostCatalogProductsProductIdUnitsConvert200>(
      {
        url: `/catalog/products/${productId}/units/convert`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerConvertUnitRequest,
      },
      options
    )
  }
  /**
   * Get the default purchase unit for a product
   * @summary Get default purchase unit
   */
  const getCatalogProductsProductIdUnitsDefaultPurchase = (
    productId: string,
    options?: SecondParameter<
      typeof customInstance<GetCatalogProductsProductIdUnitsDefaultPurchase200>
    >
  ) => {
    return customInstance<GetCatalogProductsProductIdUnitsDefaultPurchase200>(
      { url: `/catalog/products/${productId}/units/default-purchase`, method: 'GET' },
      options
    )
  }
  /**
   * Get the default sales unit for a product
   * @summary Get default sales unit
   */
  const getCatalogProductsProductIdUnitsDefaultSales = (
    productId: string,
    options?: SecondParameter<
      typeof customInstance<GetCatalogProductsProductIdUnitsDefaultSales200>
    >
  ) => {
    return customInstance<GetCatalogProductsProductIdUnitsDefaultSales200>(
      { url: `/catalog/products/${productId}/units/default-sales`, method: 'GET' },
      options
    )
  }
  return {
    getCatalogProductsProductIdUnits,
    postCatalogProductsProductIdUnits,
    deleteCatalogProductsProductIdUnitsId,
    getCatalogProductsProductIdUnitsId,
    putCatalogProductsProductIdUnitsId,
    postCatalogProductsProductIdUnitsConvert,
    getCatalogProductsProductIdUnitsDefaultPurchase,
    getCatalogProductsProductIdUnitsDefaultSales,
  }
}
export type GetCatalogProductsProductIdUnitsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['getCatalogProductsProductIdUnits']>>
>
export type PostCatalogProductsProductIdUnitsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['postCatalogProductsProductIdUnits']>>
>
export type DeleteCatalogProductsProductIdUnitsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['deleteCatalogProductsProductIdUnitsId']>>
>
export type GetCatalogProductsProductIdUnitsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['getCatalogProductsProductIdUnitsId']>>
>
export type PutCatalogProductsProductIdUnitsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProductUnits>['putCatalogProductsProductIdUnitsId']>>
>
export type PostCatalogProductsProductIdUnitsConvertResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProductUnits>['postCatalogProductsProductIdUnitsConvert']>
  >
>
export type GetCatalogProductsProductIdUnitsDefaultPurchaseResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getProductUnits>['getCatalogProductsProductIdUnitsDefaultPurchase']
    >
  >
>
export type GetCatalogProductsProductIdUnitsDefaultSalesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProductUnits>['getCatalogProductsProductIdUnitsDefaultSales']>
  >
>
