/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  GetCatalogCategories200,
  GetCatalogCategoriesId200,
  GetCatalogCategoriesIdChildren200,
  GetCatalogCategoriesParams,
  GetCatalogCategoriesRoots200,
  GetCatalogCategoriesTree200,
  HandlerCreateCategoryRequest,
  HandlerMoveCategoryRequest,
  HandlerUpdateCategoryRequest,
  PostCatalogCategories201,
  PostCatalogCategoriesIdActivate200,
  PostCatalogCategoriesIdDeactivate200,
  PostCatalogCategoriesIdMove200,
  PutCatalogCategoriesId200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getCategories = () => {
  /**
   * Retrieve a paginated list of categories
   * @summary List categories
   */
  const getCatalogCategories = (
    params?: GetCatalogCategoriesParams,
    options?: SecondParameter<typeof customInstance<GetCatalogCategories200>>
  ) => {
    return customInstance<GetCatalogCategories200>(
      { url: `/catalog/categories`, method: 'GET', params },
      options
    )
  }
  /**
   * Create a new product category. Can be a root category or a child of an existing category.
   * @summary Create a new category
   */
  const postCatalogCategories = (
    handlerCreateCategoryRequest: HandlerCreateCategoryRequest,
    options?: SecondParameter<typeof customInstance<PostCatalogCategories201>>
  ) => {
    return customInstance<PostCatalogCategories201>(
      {
        url: `/catalog/categories`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateCategoryRequest,
      },
      options
    )
  }
  /**
   * Delete a category. Category must have no children and no associated products.
   * @summary Delete a category
   */
  const deleteCatalogCategoriesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>({ url: `/catalog/categories/${id}`, method: 'DELETE' }, options)
  }
  /**
   * Retrieve a category by its ID
   * @summary Get category by ID
   */
  const getCatalogCategoriesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetCatalogCategoriesId200>>
  ) => {
    return customInstance<GetCatalogCategoriesId200>(
      { url: `/catalog/categories/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update an existing category's information
   * @summary Update a category
   */
  const putCatalogCategoriesId = (
    id: string,
    handlerUpdateCategoryRequest: HandlerUpdateCategoryRequest,
    options?: SecondParameter<typeof customInstance<PutCatalogCategoriesId200>>
  ) => {
    return customInstance<PutCatalogCategoriesId200>(
      {
        url: `/catalog/categories/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateCategoryRequest,
      },
      options
    )
  }
  /**
   * Activate an inactive category
   * @summary Activate a category
   */
  const postCatalogCategoriesIdActivate = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostCatalogCategoriesIdActivate200>>
  ) => {
    return customInstance<PostCatalogCategoriesIdActivate200>(
      { url: `/catalog/categories/${id}/activate`, method: 'POST' },
      options
    )
  }
  /**
   * Retrieve direct children of a specific category
   * @summary Get children of a category
   */
  const getCatalogCategoriesIdChildren = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetCatalogCategoriesIdChildren200>>
  ) => {
    return customInstance<GetCatalogCategoriesIdChildren200>(
      { url: `/catalog/categories/${id}/children`, method: 'GET' },
      options
    )
  }
  /**
   * Deactivate an active category
   * @summary Deactivate a category
   */
  const postCatalogCategoriesIdDeactivate = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostCatalogCategoriesIdDeactivate200>>
  ) => {
    return customInstance<PostCatalogCategoriesIdDeactivate200>(
      { url: `/catalog/categories/${id}/deactivate`, method: 'POST' },
      options
    )
  }
  /**
   * Move a category to a new parent (or make it a root category)
   * @summary Move a category
   */
  const postCatalogCategoriesIdMove = (
    id: string,
    handlerMoveCategoryRequest: HandlerMoveCategoryRequest,
    options?: SecondParameter<typeof customInstance<PostCatalogCategoriesIdMove200>>
  ) => {
    return customInstance<PostCatalogCategoriesIdMove200>(
      {
        url: `/catalog/categories/${id}/move`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerMoveCategoryRequest,
      },
      options
    )
  }
  /**
   * Retrieve all root (top-level) categories
   * @summary Get root categories
   */
  const getCatalogCategoriesRoots = (
    options?: SecondParameter<typeof customInstance<GetCatalogCategoriesRoots200>>
  ) => {
    return customInstance<GetCatalogCategoriesRoots200>(
      { url: `/catalog/categories/roots`, method: 'GET' },
      options
    )
  }
  /**
   * Retrieve all categories as a hierarchical tree structure
   * @summary Get category tree
   */
  const getCatalogCategoriesTree = (
    options?: SecondParameter<typeof customInstance<GetCatalogCategoriesTree200>>
  ) => {
    return customInstance<GetCatalogCategoriesTree200>(
      { url: `/catalog/categories/tree`, method: 'GET' },
      options
    )
  }
  return {
    getCatalogCategories,
    postCatalogCategories,
    deleteCatalogCategoriesId,
    getCatalogCategoriesId,
    putCatalogCategoriesId,
    postCatalogCategoriesIdActivate,
    getCatalogCategoriesIdChildren,
    postCatalogCategoriesIdDeactivate,
    postCatalogCategoriesIdMove,
    getCatalogCategoriesRoots,
    getCatalogCategoriesTree,
  }
}
export type GetCatalogCategoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['getCatalogCategories']>>
>
export type PostCatalogCategoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['postCatalogCategories']>>
>
export type DeleteCatalogCategoriesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['deleteCatalogCategoriesId']>>
>
export type GetCatalogCategoriesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['getCatalogCategoriesId']>>
>
export type PutCatalogCategoriesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['putCatalogCategoriesId']>>
>
export type PostCatalogCategoriesIdActivateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['postCatalogCategoriesIdActivate']>>
>
export type GetCatalogCategoriesIdChildrenResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['getCatalogCategoriesIdChildren']>>
>
export type PostCatalogCategoriesIdDeactivateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['postCatalogCategoriesIdDeactivate']>>
>
export type PostCatalogCategoriesIdMoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['postCatalogCategoriesIdMove']>>
>
export type GetCatalogCategoriesRootsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['getCatalogCategoriesRoots']>>
>
export type GetCatalogCategoriesTreeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategories>['getCatalogCategoriesTree']>>
>
