/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AddSalesReturnItemBody,
  ApproveSalesReturnBody,
  CancelSalesReturnBody,
  CompleteSalesReturnBody,
  CreateSalesReturnBody,
  DtoErrorResponse,
  HandlerAPIResponseArrayHandlerSalesReturnListResponse,
  HandlerAPIResponseHandlerReturnStatusSummaryResponse,
  HandlerAPIResponseHandlerSalesReturnResponse,
  ListSalesReturnsParams,
  ReceiveSalesReturnBody,
  RejectSalesReturnBody,
  SubmitSalesReturnBody,
  UpdateSalesReturnBody,
  UpdateSalesReturnItemBody,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retrieve a paginated list of sales returns with optional filtering
 * @summary List sales returns
 */
export type listSalesReturnsResponse200 = {
  data: HandlerAPIResponseArrayHandlerSalesReturnListResponse
  status: 200
}

export type listSalesReturnsResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type listSalesReturnsResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type listSalesReturnsResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type listSalesReturnsResponseSuccess = listSalesReturnsResponse200 & {
  headers: Headers
}
export type listSalesReturnsResponseError = (
  | listSalesReturnsResponse400
  | listSalesReturnsResponse401
  | listSalesReturnsResponse500
) & {
  headers: Headers
}

export type listSalesReturnsResponse =
  | listSalesReturnsResponseSuccess
  | listSalesReturnsResponseError

export const getListSalesReturnsUrl = (params?: ListSalesReturnsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/trade/sales-returns?${stringifiedParams}`
    : `/trade/sales-returns`
}

export const listSalesReturns = async (
  params?: ListSalesReturnsParams,
  options?: RequestInit
): Promise<listSalesReturnsResponse> => {
  return customInstance<listSalesReturnsResponse>(getListSalesReturnsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListSalesReturnsQueryKey = (params?: ListSalesReturnsParams) => {
  return [`/trade/sales-returns`, ...(params ? [params] : [])] as const
}

export const getListSalesReturnsQueryOptions = <
  TData = Awaited<ReturnType<typeof listSalesReturns>>,
  TError = DtoErrorResponse,
>(
  params?: ListSalesReturnsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listSalesReturns>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListSalesReturnsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listSalesReturns>>> = ({ signal }) =>
    listSalesReturns(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSalesReturns>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSalesReturnsQueryResult = NonNullable<Awaited<ReturnType<typeof listSalesReturns>>>
export type ListSalesReturnsQueryError = DtoErrorResponse

export function useListSalesReturns<
  TData = Awaited<ReturnType<typeof listSalesReturns>>,
  TError = DtoErrorResponse,
>(
  params: undefined | ListSalesReturnsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listSalesReturns>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSalesReturns>>,
          TError,
          Awaited<ReturnType<typeof listSalesReturns>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSalesReturns<
  TData = Awaited<ReturnType<typeof listSalesReturns>>,
  TError = DtoErrorResponse,
>(
  params?: ListSalesReturnsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listSalesReturns>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSalesReturns>>,
          TError,
          Awaited<ReturnType<typeof listSalesReturns>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSalesReturns<
  TData = Awaited<ReturnType<typeof listSalesReturns>>,
  TError = DtoErrorResponse,
>(
  params?: ListSalesReturnsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listSalesReturns>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List sales returns
 */

export function useListSalesReturns<
  TData = Awaited<ReturnType<typeof listSalesReturns>>,
  TError = DtoErrorResponse,
>(
  params?: ListSalesReturnsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listSalesReturns>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListSalesReturnsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Create a new sales return from an existing sales order
 * @summary Create a new sales return
 */
export type createSalesReturnResponse201 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 201
}

export type createSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type createSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type createSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type createSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type createSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type createSalesReturnResponseSuccess = createSalesReturnResponse201 & {
  headers: Headers
}
export type createSalesReturnResponseError = (
  | createSalesReturnResponse400
  | createSalesReturnResponse401
  | createSalesReturnResponse404
  | createSalesReturnResponse422
  | createSalesReturnResponse500
) & {
  headers: Headers
}

export type createSalesReturnResponse =
  | createSalesReturnResponseSuccess
  | createSalesReturnResponseError

export const getCreateSalesReturnUrl = () => {
  return `/trade/sales-returns`
}

export const createSalesReturn = async (
  createSalesReturnBody: CreateSalesReturnBody,
  options?: RequestInit
): Promise<createSalesReturnResponse> => {
  return customInstance<createSalesReturnResponse>(getCreateSalesReturnUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSalesReturnBody),
  })
}

export const getCreateSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSalesReturn>>,
    TError,
    { data: CreateSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSalesReturn>>,
  TError,
  { data: CreateSalesReturnBody },
  TContext
> => {
  const mutationKey = ['createSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSalesReturn>>,
    { data: CreateSalesReturnBody }
  > = (props) => {
    const { data } = props ?? {}

    return createSalesReturn(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSalesReturn>>
>
export type CreateSalesReturnMutationBody = CreateSalesReturnBody
export type CreateSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Create a new sales return
 */
export const useCreateSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSalesReturn>>,
      TError,
      { data: CreateSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createSalesReturn>>,
  TError,
  { data: CreateSalesReturnBody },
  TContext
> => {
  return useMutation(getCreateSalesReturnMutationOptions(options), queryClient)
}
/**
 * Delete a sales return (only allowed in DRAFT status)
 * @summary Delete a sales return
 */
export type deleteSalesReturnResponse204 = {
  data: void
  status: 204
}

export type deleteSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type deleteSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type deleteSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type deleteSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type deleteSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type deleteSalesReturnResponseSuccess = deleteSalesReturnResponse204 & {
  headers: Headers
}
export type deleteSalesReturnResponseError = (
  | deleteSalesReturnResponse400
  | deleteSalesReturnResponse401
  | deleteSalesReturnResponse404
  | deleteSalesReturnResponse422
  | deleteSalesReturnResponse500
) & {
  headers: Headers
}

export type deleteSalesReturnResponse =
  | deleteSalesReturnResponseSuccess
  | deleteSalesReturnResponseError

export const getDeleteSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}`
}

export const deleteSalesReturn = async (
  id: string,
  options?: RequestInit
): Promise<deleteSalesReturnResponse> => {
  return customInstance<deleteSalesReturnResponse>(getDeleteSalesReturnUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSalesReturn>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSalesReturn>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSalesReturn>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteSalesReturn(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSalesReturn>>
>

export type DeleteSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Delete a sales return
 */
export const useDeleteSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSalesReturn>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSalesReturn>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteSalesReturnMutationOptions(options), queryClient)
}
/**
 * Retrieve a sales return by its ID
 * @summary Get sales return by ID
 */
export type getSalesReturnByIdResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type getSalesReturnByIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getSalesReturnByIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getSalesReturnByIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getSalesReturnByIdResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type getSalesReturnByIdResponseSuccess = getSalesReturnByIdResponse200 & {
  headers: Headers
}
export type getSalesReturnByIdResponseError = (
  | getSalesReturnByIdResponse400
  | getSalesReturnByIdResponse401
  | getSalesReturnByIdResponse404
  | getSalesReturnByIdResponse500
) & {
  headers: Headers
}

export type getSalesReturnByIdResponse =
  | getSalesReturnByIdResponseSuccess
  | getSalesReturnByIdResponseError

export const getGetSalesReturnByIdUrl = (id: string) => {
  return `/trade/sales-returns/${id}`
}

export const getSalesReturnById = async (
  id: string,
  options?: RequestInit
): Promise<getSalesReturnByIdResponse> => {
  return customInstance<getSalesReturnByIdResponse>(getGetSalesReturnByIdUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetSalesReturnByIdQueryKey = (id: string) => {
  return [`/trade/sales-returns/${id}`] as const
}

export const getGetSalesReturnByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSalesReturnById>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnById>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSalesReturnByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSalesReturnById>>> = ({ signal }) =>
    getSalesReturnById(id, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSalesReturnById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSalesReturnByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSalesReturnById>>
>
export type GetSalesReturnByIdQueryError = DtoErrorResponse

export function useGetSalesReturnById<
  TData = Awaited<ReturnType<typeof getSalesReturnById>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSalesReturnById>>,
          TError,
          Awaited<ReturnType<typeof getSalesReturnById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSalesReturnById<
  TData = Awaited<ReturnType<typeof getSalesReturnById>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSalesReturnById>>,
          TError,
          Awaited<ReturnType<typeof getSalesReturnById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSalesReturnById<
  TData = Awaited<ReturnType<typeof getSalesReturnById>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnById>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get sales return by ID
 */

export function useGetSalesReturnById<
  TData = Awaited<ReturnType<typeof getSalesReturnById>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnById>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSalesReturnByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Update a sales return (only allowed in DRAFT status)
 * @summary Update a sales return
 */
export type updateSalesReturnResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type updateSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type updateSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type updateSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type updateSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type updateSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type updateSalesReturnResponseSuccess = updateSalesReturnResponse200 & {
  headers: Headers
}
export type updateSalesReturnResponseError = (
  | updateSalesReturnResponse400
  | updateSalesReturnResponse401
  | updateSalesReturnResponse404
  | updateSalesReturnResponse422
  | updateSalesReturnResponse500
) & {
  headers: Headers
}

export type updateSalesReturnResponse =
  | updateSalesReturnResponseSuccess
  | updateSalesReturnResponseError

export const getUpdateSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}`
}

export const updateSalesReturn = async (
  id: string,
  updateSalesReturnBody: UpdateSalesReturnBody,
  options?: RequestInit
): Promise<updateSalesReturnResponse> => {
  return customInstance<updateSalesReturnResponse>(getUpdateSalesReturnUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSalesReturnBody),
  })
}

export const getUpdateSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSalesReturn>>,
    TError,
    { id: string; data: UpdateSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSalesReturn>>,
  TError,
  { id: string; data: UpdateSalesReturnBody },
  TContext
> => {
  const mutationKey = ['updateSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSalesReturn>>,
    { id: string; data: UpdateSalesReturnBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateSalesReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSalesReturn>>
>
export type UpdateSalesReturnMutationBody = UpdateSalesReturnBody
export type UpdateSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Update a sales return
 */
export const useUpdateSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSalesReturn>>,
      TError,
      { id: string; data: UpdateSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateSalesReturn>>,
  TError,
  { id: string; data: UpdateSalesReturnBody },
  TContext
> => {
  return useMutation(getUpdateSalesReturnMutationOptions(options), queryClient)
}
/**
 * Approve a sales return (transitions from PENDING to APPROVED)
 * @summary Approve a sales return
 */
export type approveSalesReturnResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type approveSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type approveSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type approveSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type approveSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type approveSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type approveSalesReturnResponseSuccess = approveSalesReturnResponse200 & {
  headers: Headers
}
export type approveSalesReturnResponseError = (
  | approveSalesReturnResponse400
  | approveSalesReturnResponse401
  | approveSalesReturnResponse404
  | approveSalesReturnResponse422
  | approveSalesReturnResponse500
) & {
  headers: Headers
}

export type approveSalesReturnResponse =
  | approveSalesReturnResponseSuccess
  | approveSalesReturnResponseError

export const getApproveSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}/approve`
}

export const approveSalesReturn = async (
  id: string,
  approveSalesReturnBody: ApproveSalesReturnBody,
  options?: RequestInit
): Promise<approveSalesReturnResponse> => {
  return customInstance<approveSalesReturnResponse>(getApproveSalesReturnUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(approveSalesReturnBody),
  })
}

export const getApproveSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approveSalesReturn>>,
    TError,
    { id: string; data: ApproveSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof approveSalesReturn>>,
  TError,
  { id: string; data: ApproveSalesReturnBody },
  TContext
> => {
  const mutationKey = ['approveSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approveSalesReturn>>,
    { id: string; data: ApproveSalesReturnBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return approveSalesReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApproveSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof approveSalesReturn>>
>
export type ApproveSalesReturnMutationBody = ApproveSalesReturnBody
export type ApproveSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Approve a sales return
 */
export const useApproveSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approveSalesReturn>>,
      TError,
      { id: string; data: ApproveSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof approveSalesReturn>>,
  TError,
  { id: string; data: ApproveSalesReturnBody },
  TContext
> => {
  return useMutation(getApproveSalesReturnMutationOptions(options), queryClient)
}
/**
 * Cancel a sales return (from DRAFT, PENDING, or APPROVED status)
 * @summary Cancel a sales return
 */
export type cancelSalesReturnResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type cancelSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type cancelSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type cancelSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type cancelSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type cancelSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type cancelSalesReturnResponseSuccess = cancelSalesReturnResponse200 & {
  headers: Headers
}
export type cancelSalesReturnResponseError = (
  | cancelSalesReturnResponse400
  | cancelSalesReturnResponse401
  | cancelSalesReturnResponse404
  | cancelSalesReturnResponse422
  | cancelSalesReturnResponse500
) & {
  headers: Headers
}

export type cancelSalesReturnResponse =
  | cancelSalesReturnResponseSuccess
  | cancelSalesReturnResponseError

export const getCancelSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}/cancel`
}

export const cancelSalesReturn = async (
  id: string,
  cancelSalesReturnBody: CancelSalesReturnBody,
  options?: RequestInit
): Promise<cancelSalesReturnResponse> => {
  return customInstance<cancelSalesReturnResponse>(getCancelSalesReturnUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(cancelSalesReturnBody),
  })
}

export const getCancelSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelSalesReturn>>,
    TError,
    { id: string; data: CancelSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelSalesReturn>>,
  TError,
  { id: string; data: CancelSalesReturnBody },
  TContext
> => {
  const mutationKey = ['cancelSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelSalesReturn>>,
    { id: string; data: CancelSalesReturnBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return cancelSalesReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CancelSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelSalesReturn>>
>
export type CancelSalesReturnMutationBody = CancelSalesReturnBody
export type CancelSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Cancel a sales return
 */
export const useCancelSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelSalesReturn>>,
      TError,
      { id: string; data: CancelSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof cancelSalesReturn>>,
  TError,
  { id: string; data: CancelSalesReturnBody },
  TContext
> => {
  return useMutation(getCancelSalesReturnMutationOptions(options), queryClient)
}
/**
 * Mark a sales return as completed (transitions from APPROVED to COMPLETED)
 * @summary Complete a sales return
 */
export type completeSalesReturnResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type completeSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type completeSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type completeSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type completeSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type completeSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type completeSalesReturnResponseSuccess = completeSalesReturnResponse200 & {
  headers: Headers
}
export type completeSalesReturnResponseError = (
  | completeSalesReturnResponse400
  | completeSalesReturnResponse401
  | completeSalesReturnResponse404
  | completeSalesReturnResponse422
  | completeSalesReturnResponse500
) & {
  headers: Headers
}

export type completeSalesReturnResponse =
  | completeSalesReturnResponseSuccess
  | completeSalesReturnResponseError

export const getCompleteSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}/complete`
}

export const completeSalesReturn = async (
  id: string,
  completeSalesReturnBody: CompleteSalesReturnBody,
  options?: RequestInit
): Promise<completeSalesReturnResponse> => {
  return customInstance<completeSalesReturnResponse>(getCompleteSalesReturnUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(completeSalesReturnBody),
  })
}

export const getCompleteSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeSalesReturn>>,
    TError,
    { id: string; data: CompleteSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeSalesReturn>>,
  TError,
  { id: string; data: CompleteSalesReturnBody },
  TContext
> => {
  const mutationKey = ['completeSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeSalesReturn>>,
    { id: string; data: CompleteSalesReturnBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return completeSalesReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CompleteSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeSalesReturn>>
>
export type CompleteSalesReturnMutationBody = CompleteSalesReturnBody
export type CompleteSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Complete a sales return
 */
export const useCompleteSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completeSalesReturn>>,
      TError,
      { id: string; data: CompleteSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof completeSalesReturn>>,
  TError,
  { id: string; data: CompleteSalesReturnBody },
  TContext
> => {
  return useMutation(getCompleteSalesReturnMutationOptions(options), queryClient)
}
/**
 * Add a new item to a sales return (only allowed in DRAFT status)
 * @summary Add item to sales return
 */
export type addSalesReturnItemResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type addSalesReturnItemResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type addSalesReturnItemResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type addSalesReturnItemResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type addSalesReturnItemResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type addSalesReturnItemResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type addSalesReturnItemResponseSuccess = addSalesReturnItemResponse200 & {
  headers: Headers
}
export type addSalesReturnItemResponseError = (
  | addSalesReturnItemResponse400
  | addSalesReturnItemResponse401
  | addSalesReturnItemResponse404
  | addSalesReturnItemResponse422
  | addSalesReturnItemResponse500
) & {
  headers: Headers
}

export type addSalesReturnItemResponse =
  | addSalesReturnItemResponseSuccess
  | addSalesReturnItemResponseError

export const getAddSalesReturnItemUrl = (id: string) => {
  return `/trade/sales-returns/${id}/items`
}

export const addSalesReturnItem = async (
  id: string,
  addSalesReturnItemBody: AddSalesReturnItemBody,
  options?: RequestInit
): Promise<addSalesReturnItemResponse> => {
  return customInstance<addSalesReturnItemResponse>(getAddSalesReturnItemUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addSalesReturnItemBody),
  })
}

export const getAddSalesReturnItemMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addSalesReturnItem>>,
    TError,
    { id: string; data: AddSalesReturnItemBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof addSalesReturnItem>>,
  TError,
  { id: string; data: AddSalesReturnItemBody },
  TContext
> => {
  const mutationKey = ['addSalesReturnItem']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addSalesReturnItem>>,
    { id: string; data: AddSalesReturnItemBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return addSalesReturnItem(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AddSalesReturnItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof addSalesReturnItem>>
>
export type AddSalesReturnItemMutationBody = AddSalesReturnItemBody
export type AddSalesReturnItemMutationError = DtoErrorResponse

/**
 * @summary Add item to sales return
 */
export const useAddSalesReturnItem = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addSalesReturnItem>>,
      TError,
      { id: string; data: AddSalesReturnItemBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof addSalesReturnItem>>,
  TError,
  { id: string; data: AddSalesReturnItemBody },
  TContext
> => {
  return useMutation(getAddSalesReturnItemMutationOptions(options), queryClient)
}
/**
 * Remove an item from a sales return (only allowed in DRAFT status)
 * @summary Remove item from sales return
 */
export type removeSalesReturnItemResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type removeSalesReturnItemResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type removeSalesReturnItemResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type removeSalesReturnItemResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type removeSalesReturnItemResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type removeSalesReturnItemResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type removeSalesReturnItemResponseSuccess = removeSalesReturnItemResponse200 & {
  headers: Headers
}
export type removeSalesReturnItemResponseError = (
  | removeSalesReturnItemResponse400
  | removeSalesReturnItemResponse401
  | removeSalesReturnItemResponse404
  | removeSalesReturnItemResponse422
  | removeSalesReturnItemResponse500
) & {
  headers: Headers
}

export type removeSalesReturnItemResponse =
  | removeSalesReturnItemResponseSuccess
  | removeSalesReturnItemResponseError

export const getRemoveSalesReturnItemUrl = (id: string, itemId: string) => {
  return `/trade/sales-returns/${id}/items/${itemId}`
}

export const removeSalesReturnItem = async (
  id: string,
  itemId: string,
  options?: RequestInit
): Promise<removeSalesReturnItemResponse> => {
  return customInstance<removeSalesReturnItemResponse>(getRemoveSalesReturnItemUrl(id, itemId), {
    ...options,
    method: 'DELETE',
  })
}

export const getRemoveSalesReturnItemMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeSalesReturnItem>>,
    TError,
    { id: string; itemId: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeSalesReturnItem>>,
  TError,
  { id: string; itemId: string },
  TContext
> => {
  const mutationKey = ['removeSalesReturnItem']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeSalesReturnItem>>,
    { id: string; itemId: string }
  > = (props) => {
    const { id, itemId } = props ?? {}

    return removeSalesReturnItem(id, itemId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RemoveSalesReturnItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeSalesReturnItem>>
>

export type RemoveSalesReturnItemMutationError = DtoErrorResponse

/**
 * @summary Remove item from sales return
 */
export const useRemoveSalesReturnItem = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeSalesReturnItem>>,
      TError,
      { id: string; itemId: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof removeSalesReturnItem>>,
  TError,
  { id: string; itemId: string },
  TContext
> => {
  return useMutation(getRemoveSalesReturnItemMutationOptions(options), queryClient)
}
/**
 * Update an item in a sales return (only allowed in DRAFT status)
 * @summary Update return item
 */
export type updateSalesReturnItemResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type updateSalesReturnItemResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type updateSalesReturnItemResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type updateSalesReturnItemResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type updateSalesReturnItemResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type updateSalesReturnItemResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type updateSalesReturnItemResponseSuccess = updateSalesReturnItemResponse200 & {
  headers: Headers
}
export type updateSalesReturnItemResponseError = (
  | updateSalesReturnItemResponse400
  | updateSalesReturnItemResponse401
  | updateSalesReturnItemResponse404
  | updateSalesReturnItemResponse422
  | updateSalesReturnItemResponse500
) & {
  headers: Headers
}

export type updateSalesReturnItemResponse =
  | updateSalesReturnItemResponseSuccess
  | updateSalesReturnItemResponseError

export const getUpdateSalesReturnItemUrl = (id: string, itemId: string) => {
  return `/trade/sales-returns/${id}/items/${itemId}`
}

export const updateSalesReturnItem = async (
  id: string,
  itemId: string,
  updateSalesReturnItemBody: UpdateSalesReturnItemBody,
  options?: RequestInit
): Promise<updateSalesReturnItemResponse> => {
  return customInstance<updateSalesReturnItemResponse>(getUpdateSalesReturnItemUrl(id, itemId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSalesReturnItemBody),
  })
}

export const getUpdateSalesReturnItemMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSalesReturnItem>>,
    TError,
    { id: string; itemId: string; data: UpdateSalesReturnItemBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSalesReturnItem>>,
  TError,
  { id: string; itemId: string; data: UpdateSalesReturnItemBody },
  TContext
> => {
  const mutationKey = ['updateSalesReturnItem']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSalesReturnItem>>,
    { id: string; itemId: string; data: UpdateSalesReturnItemBody }
  > = (props) => {
    const { id, itemId, data } = props ?? {}

    return updateSalesReturnItem(id, itemId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateSalesReturnItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSalesReturnItem>>
>
export type UpdateSalesReturnItemMutationBody = UpdateSalesReturnItemBody
export type UpdateSalesReturnItemMutationError = DtoErrorResponse

/**
 * @summary Update return item
 */
export const useUpdateSalesReturnItem = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSalesReturnItem>>,
      TError,
      { id: string; itemId: string; data: UpdateSalesReturnItemBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateSalesReturnItem>>,
  TError,
  { id: string; itemId: string; data: UpdateSalesReturnItemBody },
  TContext
> => {
  return useMutation(getUpdateSalesReturnItemMutationOptions(options), queryClient)
}
/**
 * Start receiving returned goods into warehouse (transitions from APPROVED to RECEIVING)
 * @summary Receive returned goods
 */
export type receiveSalesReturnResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type receiveSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type receiveSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type receiveSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type receiveSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type receiveSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type receiveSalesReturnResponseSuccess = receiveSalesReturnResponse200 & {
  headers: Headers
}
export type receiveSalesReturnResponseError = (
  | receiveSalesReturnResponse400
  | receiveSalesReturnResponse401
  | receiveSalesReturnResponse404
  | receiveSalesReturnResponse422
  | receiveSalesReturnResponse500
) & {
  headers: Headers
}

export type receiveSalesReturnResponse =
  | receiveSalesReturnResponseSuccess
  | receiveSalesReturnResponseError

export const getReceiveSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}/receive`
}

export const receiveSalesReturn = async (
  id: string,
  receiveSalesReturnBody: ReceiveSalesReturnBody,
  options?: RequestInit
): Promise<receiveSalesReturnResponse> => {
  return customInstance<receiveSalesReturnResponse>(getReceiveSalesReturnUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(receiveSalesReturnBody),
  })
}

export const getReceiveSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof receiveSalesReturn>>,
    TError,
    { id: string; data: ReceiveSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof receiveSalesReturn>>,
  TError,
  { id: string; data: ReceiveSalesReturnBody },
  TContext
> => {
  const mutationKey = ['receiveSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof receiveSalesReturn>>,
    { id: string; data: ReceiveSalesReturnBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return receiveSalesReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReceiveSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof receiveSalesReturn>>
>
export type ReceiveSalesReturnMutationBody = ReceiveSalesReturnBody
export type ReceiveSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Receive returned goods
 */
export const useReceiveSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof receiveSalesReturn>>,
      TError,
      { id: string; data: ReceiveSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof receiveSalesReturn>>,
  TError,
  { id: string; data: ReceiveSalesReturnBody },
  TContext
> => {
  return useMutation(getReceiveSalesReturnMutationOptions(options), queryClient)
}
/**
 * Reject a sales return (transitions from PENDING to REJECTED)
 * @summary Reject a sales return
 */
export type rejectSalesReturnResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type rejectSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type rejectSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type rejectSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type rejectSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type rejectSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type rejectSalesReturnResponseSuccess = rejectSalesReturnResponse200 & {
  headers: Headers
}
export type rejectSalesReturnResponseError = (
  | rejectSalesReturnResponse400
  | rejectSalesReturnResponse401
  | rejectSalesReturnResponse404
  | rejectSalesReturnResponse422
  | rejectSalesReturnResponse500
) & {
  headers: Headers
}

export type rejectSalesReturnResponse =
  | rejectSalesReturnResponseSuccess
  | rejectSalesReturnResponseError

export const getRejectSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}/reject`
}

export const rejectSalesReturn = async (
  id: string,
  rejectSalesReturnBody: RejectSalesReturnBody,
  options?: RequestInit
): Promise<rejectSalesReturnResponse> => {
  return customInstance<rejectSalesReturnResponse>(getRejectSalesReturnUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rejectSalesReturnBody),
  })
}

export const getRejectSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rejectSalesReturn>>,
    TError,
    { id: string; data: RejectSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof rejectSalesReturn>>,
  TError,
  { id: string; data: RejectSalesReturnBody },
  TContext
> => {
  const mutationKey = ['rejectSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rejectSalesReturn>>,
    { id: string; data: RejectSalesReturnBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return rejectSalesReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RejectSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof rejectSalesReturn>>
>
export type RejectSalesReturnMutationBody = RejectSalesReturnBody
export type RejectSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Reject a sales return
 */
export const useRejectSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rejectSalesReturn>>,
      TError,
      { id: string; data: RejectSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof rejectSalesReturn>>,
  TError,
  { id: string; data: RejectSalesReturnBody },
  TContext
> => {
  return useMutation(getRejectSalesReturnMutationOptions(options), queryClient)
}
/**
 * Submit a sales return for approval (transitions from DRAFT to PENDING)
 * @summary Submit a sales return for approval
 */
export type submitSalesReturnResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type submitSalesReturnResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type submitSalesReturnResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type submitSalesReturnResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type submitSalesReturnResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type submitSalesReturnResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type submitSalesReturnResponseSuccess = submitSalesReturnResponse200 & {
  headers: Headers
}
export type submitSalesReturnResponseError = (
  | submitSalesReturnResponse400
  | submitSalesReturnResponse401
  | submitSalesReturnResponse404
  | submitSalesReturnResponse422
  | submitSalesReturnResponse500
) & {
  headers: Headers
}

export type submitSalesReturnResponse =
  | submitSalesReturnResponseSuccess
  | submitSalesReturnResponseError

export const getSubmitSalesReturnUrl = (id: string) => {
  return `/trade/sales-returns/${id}/submit`
}

export const submitSalesReturn = async (
  id: string,
  submitSalesReturnBody: SubmitSalesReturnBody,
  options?: RequestInit
): Promise<submitSalesReturnResponse> => {
  return customInstance<submitSalesReturnResponse>(getSubmitSalesReturnUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitSalesReturnBody),
  })
}

export const getSubmitSalesReturnMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitSalesReturn>>,
    TError,
    { id: string; data: SubmitSalesReturnBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitSalesReturn>>,
  TError,
  { id: string; data: SubmitSalesReturnBody },
  TContext
> => {
  const mutationKey = ['submitSalesReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitSalesReturn>>,
    { id: string; data: SubmitSalesReturnBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return submitSalesReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SubmitSalesReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitSalesReturn>>
>
export type SubmitSalesReturnMutationBody = SubmitSalesReturnBody
export type SubmitSalesReturnMutationError = DtoErrorResponse

/**
 * @summary Submit a sales return for approval
 */
export const useSubmitSalesReturn = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitSalesReturn>>,
      TError,
      { id: string; data: SubmitSalesReturnBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof submitSalesReturn>>,
  TError,
  { id: string; data: SubmitSalesReturnBody },
  TContext
> => {
  return useMutation(getSubmitSalesReturnMutationOptions(options), queryClient)
}
/**
 * Retrieve a sales return by its return number
 * @summary Get sales return by return number
 */
export type getSalesReturnByReturnNumberResponse200 = {
  data: HandlerAPIResponseHandlerSalesReturnResponse
  status: 200
}

export type getSalesReturnByReturnNumberResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getSalesReturnByReturnNumberResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getSalesReturnByReturnNumberResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getSalesReturnByReturnNumberResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type getSalesReturnByReturnNumberResponseSuccess =
  getSalesReturnByReturnNumberResponse200 & {
    headers: Headers
  }
export type getSalesReturnByReturnNumberResponseError = (
  | getSalesReturnByReturnNumberResponse400
  | getSalesReturnByReturnNumberResponse401
  | getSalesReturnByReturnNumberResponse404
  | getSalesReturnByReturnNumberResponse500
) & {
  headers: Headers
}

export type getSalesReturnByReturnNumberResponse =
  | getSalesReturnByReturnNumberResponseSuccess
  | getSalesReturnByReturnNumberResponseError

export const getGetSalesReturnByReturnNumberUrl = (returnNumber: string) => {
  return `/trade/sales-returns/number/${returnNumber}`
}

export const getSalesReturnByReturnNumber = async (
  returnNumber: string,
  options?: RequestInit
): Promise<getSalesReturnByReturnNumberResponse> => {
  return customInstance<getSalesReturnByReturnNumberResponse>(
    getGetSalesReturnByReturnNumberUrl(returnNumber),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetSalesReturnByReturnNumberQueryKey = (returnNumber: string) => {
  return [`/trade/sales-returns/number/${returnNumber}`] as const
}

export const getGetSalesReturnByReturnNumberQueryOptions = <
  TData = Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
  TError = DtoErrorResponse,
>(
  returnNumber: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSalesReturnByReturnNumberQueryKey(returnNumber)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>> = ({
    signal,
  }) => getSalesReturnByReturnNumber(returnNumber, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: !!returnNumber, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSalesReturnByReturnNumberQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>
>
export type GetSalesReturnByReturnNumberQueryError = DtoErrorResponse

export function useGetSalesReturnByReturnNumber<
  TData = Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
  TError = DtoErrorResponse,
>(
  returnNumber: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
          TError,
          Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSalesReturnByReturnNumber<
  TData = Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
  TError = DtoErrorResponse,
>(
  returnNumber: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
          TError,
          Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSalesReturnByReturnNumber<
  TData = Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
  TError = DtoErrorResponse,
>(
  returnNumber: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get sales return by return number
 */

export function useGetSalesReturnByReturnNumber<
  TData = Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>,
  TError = DtoErrorResponse,
>(
  returnNumber: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnByReturnNumber>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSalesReturnByReturnNumberQueryOptions(returnNumber, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Get count of returns by status for dashboard
 * @summary Get return status summary
 */
export type getSalesReturnStatusSummaryResponse200 = {
  data: HandlerAPIResponseHandlerReturnStatusSummaryResponse
  status: 200
}

export type getSalesReturnStatusSummaryResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getSalesReturnStatusSummaryResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getSalesReturnStatusSummaryResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type getSalesReturnStatusSummaryResponseSuccess = getSalesReturnStatusSummaryResponse200 & {
  headers: Headers
}
export type getSalesReturnStatusSummaryResponseError = (
  | getSalesReturnStatusSummaryResponse400
  | getSalesReturnStatusSummaryResponse401
  | getSalesReturnStatusSummaryResponse500
) & {
  headers: Headers
}

export type getSalesReturnStatusSummaryResponse =
  | getSalesReturnStatusSummaryResponseSuccess
  | getSalesReturnStatusSummaryResponseError

export const getGetSalesReturnStatusSummaryUrl = () => {
  return `/trade/sales-returns/stats/summary`
}

export const getSalesReturnStatusSummary = async (
  options?: RequestInit
): Promise<getSalesReturnStatusSummaryResponse> => {
  return customInstance<getSalesReturnStatusSummaryResponse>(getGetSalesReturnStatusSummaryUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetSalesReturnStatusSummaryQueryKey = () => {
  return [`/trade/sales-returns/stats/summary`] as const
}

export const getGetSalesReturnStatusSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
  TError = DtoErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnStatusSummary>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSalesReturnStatusSummaryQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSalesReturnStatusSummary>>> = ({
    signal,
  }) => getSalesReturnStatusSummary({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSalesReturnStatusSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSalesReturnStatusSummary>>
>
export type GetSalesReturnStatusSummaryQueryError = DtoErrorResponse

export function useGetSalesReturnStatusSummary<
  TData = Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
  TError = DtoErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnStatusSummary>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
          TError,
          Awaited<ReturnType<typeof getSalesReturnStatusSummary>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSalesReturnStatusSummary<
  TData = Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
  TError = DtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnStatusSummary>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
          TError,
          Awaited<ReturnType<typeof getSalesReturnStatusSummary>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSalesReturnStatusSummary<
  TData = Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
  TError = DtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnStatusSummary>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get return status summary
 */

export function useGetSalesReturnStatusSummary<
  TData = Awaited<ReturnType<typeof getSalesReturnStatusSummary>>,
  TError = DtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSalesReturnStatusSummary>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSalesReturnStatusSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
