/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  DtoErrorResponse,
  GeneratePDFPrintJobBody,
  HandlerAPIResponseArrayHandlerPrintJobResponse,
  HandlerAPIResponseHandlerPrintJobResponse,
  ListPrintJobJobsParams,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Generate a PDF for a document and create a print job
 * @summary Generate PDF
 */
export type generatePDFPrintJobResponse201 = {
  data: HandlerAPIResponseHandlerPrintJobResponse
  status: 201
}

export type generatePDFPrintJobResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type generatePDFPrintJobResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type generatePDFPrintJobResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type generatePDFPrintJobResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type generatePDFPrintJobResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type generatePDFPrintJobResponseSuccess = generatePDFPrintJobResponse201 & {
  headers: Headers
}
export type generatePDFPrintJobResponseError = (
  | generatePDFPrintJobResponse400
  | generatePDFPrintJobResponse401
  | generatePDFPrintJobResponse404
  | generatePDFPrintJobResponse422
  | generatePDFPrintJobResponse500
) & {
  headers: Headers
}

export type generatePDFPrintJobResponse =
  | generatePDFPrintJobResponseSuccess
  | generatePDFPrintJobResponseError

export const getGeneratePDFPrintJobUrl = () => {
  return `/print/generate`
}

export const generatePDFPrintJob = async (
  generatePDFPrintJobBody: GeneratePDFPrintJobBody,
  options?: RequestInit
): Promise<generatePDFPrintJobResponse> => {
  return customInstance<generatePDFPrintJobResponse>(getGeneratePDFPrintJobUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(generatePDFPrintJobBody),
  })
}

export const getGeneratePDFPrintJobMutationOptions = <
  TError = DtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generatePDFPrintJob>>,
    TError,
    { data: GeneratePDFPrintJobBody },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof generatePDFPrintJob>>,
  TError,
  { data: GeneratePDFPrintJobBody },
  TContext
> => {
  const mutationKey = ['generatePDFPrintJob']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generatePDFPrintJob>>,
    { data: GeneratePDFPrintJobBody }
  > = (props) => {
    const { data } = props ?? {}

    return generatePDFPrintJob(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GeneratePDFPrintJobMutationResult = NonNullable<
  Awaited<ReturnType<typeof generatePDFPrintJob>>
>
export type GeneratePDFPrintJobMutationBody = GeneratePDFPrintJobBody
export type GeneratePDFPrintJobMutationError = DtoErrorResponse

/**
 * @summary Generate PDF
 */
export const useGeneratePDFPrintJob = <TError = DtoErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generatePDFPrintJob>>,
      TError,
      { data: GeneratePDFPrintJobBody },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof generatePDFPrintJob>>,
  TError,
  { data: GeneratePDFPrintJobBody },
  TContext
> => {
  return useMutation(getGeneratePDFPrintJobMutationOptions(options), queryClient)
}
/**
 * Retrieve a paginated list of print jobs
 * @summary List print jobs
 */
export type listPrintJobJobsResponse200 = {
  data: HandlerAPIResponseArrayHandlerPrintJobResponse
  status: 200
}

export type listPrintJobJobsResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type listPrintJobJobsResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type listPrintJobJobsResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type listPrintJobJobsResponseSuccess = listPrintJobJobsResponse200 & {
  headers: Headers
}
export type listPrintJobJobsResponseError = (
  | listPrintJobJobsResponse400
  | listPrintJobJobsResponse401
  | listPrintJobJobsResponse500
) & {
  headers: Headers
}

export type listPrintJobJobsResponse =
  | listPrintJobJobsResponseSuccess
  | listPrintJobJobsResponseError

export const getListPrintJobJobsUrl = (params?: ListPrintJobJobsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/print/jobs?${stringifiedParams}` : `/print/jobs`
}

export const listPrintJobJobs = async (
  params?: ListPrintJobJobsParams,
  options?: RequestInit
): Promise<listPrintJobJobsResponse> => {
  return customInstance<listPrintJobJobsResponse>(getListPrintJobJobsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListPrintJobJobsQueryKey = (params?: ListPrintJobJobsParams) => {
  return [`/print/jobs`, ...(params ? [params] : [])] as const
}

export const getListPrintJobJobsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPrintJobJobs>>,
  TError = DtoErrorResponse,
>(
  params?: ListPrintJobJobsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPrintJobJobs>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListPrintJobJobsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPrintJobJobs>>> = ({ signal }) =>
    listPrintJobJobs(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPrintJobJobs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPrintJobJobsQueryResult = NonNullable<Awaited<ReturnType<typeof listPrintJobJobs>>>
export type ListPrintJobJobsQueryError = DtoErrorResponse

export function useListPrintJobJobs<
  TData = Awaited<ReturnType<typeof listPrintJobJobs>>,
  TError = DtoErrorResponse,
>(
  params: undefined | ListPrintJobJobsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPrintJobJobs>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPrintJobJobs>>,
          TError,
          Awaited<ReturnType<typeof listPrintJobJobs>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPrintJobJobs<
  TData = Awaited<ReturnType<typeof listPrintJobJobs>>,
  TError = DtoErrorResponse,
>(
  params?: ListPrintJobJobsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPrintJobJobs>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPrintJobJobs>>,
          TError,
          Awaited<ReturnType<typeof listPrintJobJobs>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPrintJobJobs<
  TData = Awaited<ReturnType<typeof listPrintJobJobs>>,
  TError = DtoErrorResponse,
>(
  params?: ListPrintJobJobsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPrintJobJobs>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List print jobs
 */

export function useListPrintJobJobs<
  TData = Awaited<ReturnType<typeof listPrintJobJobs>>,
  TError = DtoErrorResponse,
>(
  params?: ListPrintJobJobsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPrintJobJobs>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListPrintJobJobsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Retrieve a print job by its ID
 * @summary Get print job by ID
 */
export type getPrintJobJobResponse200 = {
  data: HandlerAPIResponseHandlerPrintJobResponse
  status: 200
}

export type getPrintJobJobResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getPrintJobJobResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getPrintJobJobResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getPrintJobJobResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type getPrintJobJobResponseSuccess = getPrintJobJobResponse200 & {
  headers: Headers
}
export type getPrintJobJobResponseError = (
  | getPrintJobJobResponse400
  | getPrintJobJobResponse401
  | getPrintJobJobResponse404
  | getPrintJobJobResponse500
) & {
  headers: Headers
}

export type getPrintJobJobResponse = getPrintJobJobResponseSuccess | getPrintJobJobResponseError

export const getGetPrintJobJobUrl = (id: string) => {
  return `/print/jobs/${id}`
}

export const getPrintJobJob = async (
  id: string,
  options?: RequestInit
): Promise<getPrintJobJobResponse> => {
  return customInstance<getPrintJobJobResponse>(getGetPrintJobJobUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetPrintJobJobQueryKey = (id: string) => {
  return [`/print/jobs/${id}`] as const
}

export const getGetPrintJobJobQueryOptions = <
  TData = Awaited<ReturnType<typeof getPrintJobJob>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJob>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPrintJobJobQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrintJobJob>>> = ({ signal }) =>
    getPrintJobJob(id, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPrintJobJob>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPrintJobJobQueryResult = NonNullable<Awaited<ReturnType<typeof getPrintJobJob>>>
export type GetPrintJobJobQueryError = DtoErrorResponse

export function useGetPrintJobJob<
  TData = Awaited<ReturnType<typeof getPrintJobJob>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJob>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrintJobJob>>,
          TError,
          Awaited<ReturnType<typeof getPrintJobJob>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrintJobJob<
  TData = Awaited<ReturnType<typeof getPrintJobJob>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJob>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrintJobJob>>,
          TError,
          Awaited<ReturnType<typeof getPrintJobJob>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrintJobJob<
  TData = Awaited<ReturnType<typeof getPrintJobJob>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJob>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get print job by ID
 */

export function useGetPrintJobJob<
  TData = Awaited<ReturnType<typeof getPrintJobJob>>,
  TError = DtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJob>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPrintJobJobQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Download the PDF file for a completed print job
 * @summary Download PDF
 */
export type downloadPDFPrintJobResponse200 = {
  data: Blob
  status: 200
}

export type downloadPDFPrintJobResponse400 = {
  data: Blob
  status: 400
}

export type downloadPDFPrintJobResponse401 = {
  data: Blob
  status: 401
}

export type downloadPDFPrintJobResponse404 = {
  data: Blob
  status: 404
}

export type downloadPDFPrintJobResponse500 = {
  data: Blob
  status: 500
}

export type downloadPDFPrintJobResponseSuccess = downloadPDFPrintJobResponse200 & {
  headers: Headers
}
export type downloadPDFPrintJobResponseError = (
  | downloadPDFPrintJobResponse400
  | downloadPDFPrintJobResponse401
  | downloadPDFPrintJobResponse404
  | downloadPDFPrintJobResponse500
) & {
  headers: Headers
}

export type downloadPDFPrintJobResponse =
  | downloadPDFPrintJobResponseSuccess
  | downloadPDFPrintJobResponseError

export const getDownloadPDFPrintJobUrl = (id: string) => {
  return `/print/jobs/${id}/download`
}

export const downloadPDFPrintJob = async (
  id: string,
  options?: RequestInit
): Promise<downloadPDFPrintJobResponse> => {
  return customInstance<downloadPDFPrintJobResponse>(getDownloadPDFPrintJobUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getDownloadPDFPrintJobQueryKey = (id: string) => {
  return [`/print/jobs/${id}/download`] as const
}

export const getDownloadPDFPrintJobQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadPDFPrintJob>>,
  TError = Blob,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadPDFPrintJob>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDownloadPDFPrintJobQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadPDFPrintJob>>> = ({ signal }) =>
    downloadPDFPrintJob(id, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadPDFPrintJob>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadPDFPrintJobQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadPDFPrintJob>>
>
export type DownloadPDFPrintJobQueryError = Blob

export function useDownloadPDFPrintJob<
  TData = Awaited<ReturnType<typeof downloadPDFPrintJob>>,
  TError = Blob,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadPDFPrintJob>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadPDFPrintJob>>,
          TError,
          Awaited<ReturnType<typeof downloadPDFPrintJob>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadPDFPrintJob<
  TData = Awaited<ReturnType<typeof downloadPDFPrintJob>>,
  TError = Blob,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadPDFPrintJob>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadPDFPrintJob>>,
          TError,
          Awaited<ReturnType<typeof downloadPDFPrintJob>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadPDFPrintJob<
  TData = Awaited<ReturnType<typeof downloadPDFPrintJob>>,
  TError = Blob,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadPDFPrintJob>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download PDF
 */

export function useDownloadPDFPrintJob<
  TData = Awaited<ReturnType<typeof downloadPDFPrintJob>>,
  TError = Blob,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadPDFPrintJob>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDownloadPDFPrintJobQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Retrieve print jobs for a specific document
 * @summary Get jobs by document
 */
export type getPrintJobJobsByDocumentResponse200 = {
  data: HandlerAPIResponseArrayHandlerPrintJobResponse
  status: 200
}

export type getPrintJobJobsByDocumentResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getPrintJobJobsByDocumentResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getPrintJobJobsByDocumentResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type getPrintJobJobsByDocumentResponseSuccess = getPrintJobJobsByDocumentResponse200 & {
  headers: Headers
}
export type getPrintJobJobsByDocumentResponseError = (
  | getPrintJobJobsByDocumentResponse400
  | getPrintJobJobsByDocumentResponse401
  | getPrintJobJobsByDocumentResponse500
) & {
  headers: Headers
}

export type getPrintJobJobsByDocumentResponse =
  | getPrintJobJobsByDocumentResponseSuccess
  | getPrintJobJobsByDocumentResponseError

export const getGetPrintJobJobsByDocumentUrl = (docType: string, documentId: string) => {
  return `/print/jobs/by-document/${docType}/${documentId}`
}

export const getPrintJobJobsByDocument = async (
  docType: string,
  documentId: string,
  options?: RequestInit
): Promise<getPrintJobJobsByDocumentResponse> => {
  return customInstance<getPrintJobJobsByDocumentResponse>(
    getGetPrintJobJobsByDocumentUrl(docType, documentId),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetPrintJobJobsByDocumentQueryKey = (docType: string, documentId: string) => {
  return [`/print/jobs/by-document/${docType}/${documentId}`] as const
}

export const getGetPrintJobJobsByDocumentQueryOptions = <
  TData = Awaited<ReturnType<typeof getPrintJobJobsByDocument>>,
  TError = DtoErrorResponse,
>(
  docType: string,
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJobsByDocument>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetPrintJobJobsByDocumentQueryKey(docType, documentId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrintJobJobsByDocument>>> = ({
    signal,
  }) => getPrintJobJobsByDocument(docType, documentId, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!(docType && documentId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJobsByDocument>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetPrintJobJobsByDocumentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPrintJobJobsByDocument>>
>
export type GetPrintJobJobsByDocumentQueryError = DtoErrorResponse

export function useGetPrintJobJobsByDocument<
  TData = Awaited<ReturnType<typeof getPrintJobJobsByDocument>>,
  TError = DtoErrorResponse,
>(
  docType: string,
  documentId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJobsByDocument>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrintJobJobsByDocument>>,
          TError,
          Awaited<ReturnType<typeof getPrintJobJobsByDocument>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrintJobJobsByDocument<
  TData = Awaited<ReturnType<typeof getPrintJobJobsByDocument>>,
  TError = DtoErrorResponse,
>(
  docType: string,
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJobsByDocument>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrintJobJobsByDocument>>,
          TError,
          Awaited<ReturnType<typeof getPrintJobJobsByDocument>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrintJobJobsByDocument<
  TData = Awaited<ReturnType<typeof getPrintJobJobsByDocument>>,
  TError = DtoErrorResponse,
>(
  docType: string,
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJobsByDocument>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get jobs by document
 */

export function useGetPrintJobJobsByDocument<
  TData = Awaited<ReturnType<typeof getPrintJobJobsByDocument>>,
  TError = DtoErrorResponse,
>(
  docType: string,
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPrintJobJobsByDocument>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPrintJobJobsByDocumentQueryOptions(docType, documentId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
