/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DtoResponse,
  GetIdentityPermissions200,
  GetIdentityRoles200,
  GetIdentityRolesCodeCode200,
  GetIdentityRolesId200,
  GetIdentityRolesParams,
  GetIdentityRolesStatsCount200,
  GetIdentityRolesSystem200,
  HandlerCreateRoleRequest,
  HandlerSetPermissionsRequest,
  HandlerUpdateRoleRequest,
  PostIdentityRoles201,
  PostIdentityRolesIdDisable200,
  PostIdentityRolesIdEnable200,
  PutIdentityRolesId200,
  PutIdentityRolesIdPermissions200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getRoles = () => {
  /**
   * Get all available permission codes
   * @summary Get all available permissions
   */
  const getIdentityPermissions = (
    options?: SecondParameter<typeof customInstance<GetIdentityPermissions200>>
  ) => {
    return customInstance<GetIdentityPermissions200>(
      { url: `/identity/permissions`, method: 'GET' },
      options
    )
  }
  /**
   * Get a paginated list of roles
   * @summary List roles
   */
  const getIdentityRoles = (
    params?: GetIdentityRolesParams,
    options?: SecondParameter<typeof customInstance<GetIdentityRoles200>>
  ) => {
    return customInstance<GetIdentityRoles200>(
      { url: `/identity/roles`, method: 'GET', params },
      options
    )
  }
  /**
   * Create a new role in the system
   * @summary Create a new role
   */
  const postIdentityRoles = (
    handlerCreateRoleRequest: HandlerCreateRoleRequest,
    options?: SecondParameter<typeof customInstance<PostIdentityRoles201>>
  ) => {
    return customInstance<PostIdentityRoles201>(
      {
        url: `/identity/roles`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateRoleRequest,
      },
      options
    )
  }
  /**
   * Delete a role from the system
   * @summary Delete a role
   */
  const deleteIdentityRolesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<DtoResponse>>
  ) => {
    return customInstance<DtoResponse>({ url: `/identity/roles/${id}`, method: 'DELETE' }, options)
  }
  /**
   * Retrieve a role by its ID
   * @summary Get a role by ID
   */
  const getIdentityRolesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetIdentityRolesId200>>
  ) => {
    return customInstance<GetIdentityRolesId200>(
      { url: `/identity/roles/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update a role's information
   * @summary Update a role
   */
  const putIdentityRolesId = (
    id: string,
    handlerUpdateRoleRequest: HandlerUpdateRoleRequest,
    options?: SecondParameter<typeof customInstance<PutIdentityRolesId200>>
  ) => {
    return customInstance<PutIdentityRolesId200>(
      {
        url: `/identity/roles/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateRoleRequest,
      },
      options
    )
  }
  /**
   * Disable a role
   * @summary Disable a role
   */
  const postIdentityRolesIdDisable = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostIdentityRolesIdDisable200>>
  ) => {
    return customInstance<PostIdentityRolesIdDisable200>(
      { url: `/identity/roles/${id}/disable`, method: 'POST' },
      options
    )
  }
  /**
   * Enable a role
   * @summary Enable a role
   */
  const postIdentityRolesIdEnable = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostIdentityRolesIdEnable200>>
  ) => {
    return customInstance<PostIdentityRolesIdEnable200>(
      { url: `/identity/roles/${id}/enable`, method: 'POST' },
      options
    )
  }
  /**
   * Set permissions for a role (replaces existing permissions)
   * @summary Set role permissions
   */
  const putIdentityRolesIdPermissions = (
    id: string,
    handlerSetPermissionsRequest: HandlerSetPermissionsRequest,
    options?: SecondParameter<typeof customInstance<PutIdentityRolesIdPermissions200>>
  ) => {
    return customInstance<PutIdentityRolesIdPermissions200>(
      {
        url: `/identity/roles/${id}/permissions`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerSetPermissionsRequest,
      },
      options
    )
  }
  /**
   * Retrieve a role by its code
   * @summary Get a role by code
   */
  const getIdentityRolesCodeCode = (
    code: string,
    options?: SecondParameter<typeof customInstance<GetIdentityRolesCodeCode200>>
  ) => {
    return customInstance<GetIdentityRolesCodeCode200>(
      { url: `/identity/roles/code/${code}`, method: 'GET' },
      options
    )
  }
  /**
   * Get the total number of roles
   * @summary Get role count
   */
  const getIdentityRolesStatsCount = (
    options?: SecondParameter<typeof customInstance<GetIdentityRolesStatsCount200>>
  ) => {
    return customInstance<GetIdentityRolesStatsCount200>(
      { url: `/identity/roles/stats/count`, method: 'GET' },
      options
    )
  }
  /**
   * Get all system roles
   * @summary Get system roles
   */
  const getIdentityRolesSystem = (
    options?: SecondParameter<typeof customInstance<GetIdentityRolesSystem200>>
  ) => {
    return customInstance<GetIdentityRolesSystem200>(
      { url: `/identity/roles/system`, method: 'GET' },
      options
    )
  }
  return {
    getIdentityPermissions,
    getIdentityRoles,
    postIdentityRoles,
    deleteIdentityRolesId,
    getIdentityRolesId,
    putIdentityRolesId,
    postIdentityRolesIdDisable,
    postIdentityRolesIdEnable,
    putIdentityRolesIdPermissions,
    getIdentityRolesCodeCode,
    getIdentityRolesStatsCount,
    getIdentityRolesSystem,
  }
}
export type GetIdentityPermissionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['getIdentityPermissions']>>
>
export type GetIdentityRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['getIdentityRoles']>>
>
export type PostIdentityRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['postIdentityRoles']>>
>
export type DeleteIdentityRolesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['deleteIdentityRolesId']>>
>
export type GetIdentityRolesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['getIdentityRolesId']>>
>
export type PutIdentityRolesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['putIdentityRolesId']>>
>
export type PostIdentityRolesIdDisableResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['postIdentityRolesIdDisable']>>
>
export type PostIdentityRolesIdEnableResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['postIdentityRolesIdEnable']>>
>
export type PutIdentityRolesIdPermissionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['putIdentityRolesIdPermissions']>>
>
export type GetIdentityRolesCodeCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['getIdentityRolesCodeCode']>>
>
export type GetIdentityRolesStatsCountResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['getIdentityRolesStatsCount']>>
>
export type GetIdentityRolesSystemResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRoles>['getIdentityRolesSystem']>>
>
