/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DtoResponse,
  GetFinanceCashFlow200,
  GetFinanceCashFlowParams,
  GetFinanceExpenses200,
  GetFinanceExpensesId200,
  GetFinanceExpensesParams,
  GetFinanceExpensesSummary200,
  GetFinanceExpensesSummaryParams,
  HandlerCreateExpenseRecordRequest,
  HandlerExpenseActionRequest,
  HandlerMarkExpensePaidRequest,
  HandlerUpdateExpenseRecordRequest,
  PostFinanceExpenses201,
  PostFinanceExpensesIdApprove200,
  PostFinanceExpensesIdCancel200,
  PostFinanceExpensesIdPay200,
  PostFinanceExpensesIdReject200,
  PostFinanceExpensesIdSubmit200,
  PutFinanceExpensesId200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getExpenses = () => {
  /**
   * Get combined expense and income cash flow summary
   * @summary Get cash flow summary
   */
  const getFinanceCashFlow = (
    params?: GetFinanceCashFlowParams,
    options?: SecondParameter<typeof customInstance<GetFinanceCashFlow200>>
  ) => {
    return customInstance<GetFinanceCashFlow200>(
      { url: `/finance/cash-flow`, method: 'GET', params },
      options
    )
  }
  /**
   * Get a paginated list of expense records
   * @summary List expense records
   */
  const getFinanceExpenses = (
    params?: GetFinanceExpensesParams,
    options?: SecondParameter<typeof customInstance<GetFinanceExpenses200>>
  ) => {
    return customInstance<GetFinanceExpenses200>(
      { url: `/finance/expenses`, method: 'GET', params },
      options
    )
  }
  /**
   * Create a new expense record
   * @summary Create expense record
   */
  const postFinanceExpenses = (
    handlerCreateExpenseRecordRequest: HandlerCreateExpenseRecordRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceExpenses201>>
  ) => {
    return customInstance<PostFinanceExpenses201>(
      {
        url: `/finance/expenses`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerCreateExpenseRecordRequest,
      },
      options
    )
  }
  /**
   * Delete an expense record (soft delete, only draft status)
   * @summary Delete expense record
   */
  const deleteFinanceExpensesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<DtoResponse>>
  ) => {
    return customInstance<DtoResponse>(
      { url: `/finance/expenses/${id}`, method: 'DELETE' },
      options
    )
  }
  /**
   * Get a single expense record by its ID
   * @summary Get expense record by ID
   */
  const getFinanceExpensesId = (
    id: string,
    options?: SecondParameter<typeof customInstance<GetFinanceExpensesId200>>
  ) => {
    return customInstance<GetFinanceExpensesId200>(
      { url: `/finance/expenses/${id}`, method: 'GET' },
      options
    )
  }
  /**
   * Update an existing expense record (only draft status)
   * @summary Update expense record
   */
  const putFinanceExpensesId = (
    id: string,
    handlerUpdateExpenseRecordRequest: HandlerUpdateExpenseRecordRequest,
    options?: SecondParameter<typeof customInstance<PutFinanceExpensesId200>>
  ) => {
    return customInstance<PutFinanceExpensesId200>(
      {
        url: `/finance/expenses/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlerUpdateExpenseRecordRequest,
      },
      options
    )
  }
  /**
   * Approve an expense record
   * @summary Approve expense
   */
  const postFinanceExpensesIdApprove = (
    id: string,
    handlerExpenseActionRequest: HandlerExpenseActionRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceExpensesIdApprove200>>
  ) => {
    return customInstance<PostFinanceExpensesIdApprove200>(
      {
        url: `/finance/expenses/${id}/approve`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerExpenseActionRequest,
      },
      options
    )
  }
  /**
   * Cancel an expense record
   * @summary Cancel expense
   */
  const postFinanceExpensesIdCancel = (
    id: string,
    handlerExpenseActionRequest: HandlerExpenseActionRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceExpensesIdCancel200>>
  ) => {
    return customInstance<PostFinanceExpensesIdCancel200>(
      {
        url: `/finance/expenses/${id}/cancel`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerExpenseActionRequest,
      },
      options
    )
  }
  /**
   * Mark an approved expense as paid
   * @summary Mark expense as paid
   */
  const postFinanceExpensesIdPay = (
    id: string,
    handlerMarkExpensePaidRequest: HandlerMarkExpensePaidRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceExpensesIdPay200>>
  ) => {
    return customInstance<PostFinanceExpensesIdPay200>(
      {
        url: `/finance/expenses/${id}/pay`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerMarkExpensePaidRequest,
      },
      options
    )
  }
  /**
   * Reject an expense record
   * @summary Reject expense
   */
  const postFinanceExpensesIdReject = (
    id: string,
    handlerExpenseActionRequest: HandlerExpenseActionRequest,
    options?: SecondParameter<typeof customInstance<PostFinanceExpensesIdReject200>>
  ) => {
    return customInstance<PostFinanceExpensesIdReject200>(
      {
        url: `/finance/expenses/${id}/reject`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerExpenseActionRequest,
      },
      options
    )
  }
  /**
   * Submit an expense record for approval
   * @summary Submit expense for approval
   */
  const postFinanceExpensesIdSubmit = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostFinanceExpensesIdSubmit200>>
  ) => {
    return customInstance<PostFinanceExpensesIdSubmit200>(
      { url: `/finance/expenses/${id}/submit`, method: 'POST' },
      options
    )
  }
  /**
   * Get expense statistics summary
   * @summary Get expenses summary
   */
  const getFinanceExpensesSummary = (
    params?: GetFinanceExpensesSummaryParams,
    options?: SecondParameter<typeof customInstance<GetFinanceExpensesSummary200>>
  ) => {
    return customInstance<GetFinanceExpensesSummary200>(
      { url: `/finance/expenses/summary`, method: 'GET', params },
      options
    )
  }
  return {
    getFinanceCashFlow,
    getFinanceExpenses,
    postFinanceExpenses,
    deleteFinanceExpensesId,
    getFinanceExpensesId,
    putFinanceExpensesId,
    postFinanceExpensesIdApprove,
    postFinanceExpensesIdCancel,
    postFinanceExpensesIdPay,
    postFinanceExpensesIdReject,
    postFinanceExpensesIdSubmit,
    getFinanceExpensesSummary,
  }
}
export type GetFinanceCashFlowResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['getFinanceCashFlow']>>
>
export type GetFinanceExpensesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['getFinanceExpenses']>>
>
export type PostFinanceExpensesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['postFinanceExpenses']>>
>
export type DeleteFinanceExpensesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['deleteFinanceExpensesId']>>
>
export type GetFinanceExpensesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['getFinanceExpensesId']>>
>
export type PutFinanceExpensesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['putFinanceExpensesId']>>
>
export type PostFinanceExpensesIdApproveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['postFinanceExpensesIdApprove']>>
>
export type PostFinanceExpensesIdCancelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['postFinanceExpensesIdCancel']>>
>
export type PostFinanceExpensesIdPayResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['postFinanceExpensesIdPay']>>
>
export type PostFinanceExpensesIdRejectResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['postFinanceExpensesIdReject']>>
>
export type PostFinanceExpensesIdSubmitResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['postFinanceExpensesIdSubmit']>>
>
export type GetFinanceExpensesSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getExpenses>['getFinanceExpensesSummary']>>
>
