/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  GetReportsFinanceCashFlow200,
  GetReportsFinanceCashFlowItems200,
  GetReportsFinanceCashFlowItemsParams,
  GetReportsFinanceCashFlowParams,
  GetReportsFinanceMonthlyTrend200,
  GetReportsFinanceMonthlyTrendParams,
  GetReportsFinanceProfitByProduct200,
  GetReportsFinanceProfitByProductParams,
  GetReportsFinanceProfitLoss200,
  GetReportsFinanceProfitLossParams,
  GetReportsInventorySlowMoving200,
  GetReportsInventorySlowMovingParams,
  GetReportsInventorySummary200,
  GetReportsInventorySummaryParams,
  GetReportsInventoryTurnover200,
  GetReportsInventoryTurnoverParams,
  GetReportsInventoryValueByCategory200,
  GetReportsInventoryValueByCategoryParams,
  GetReportsInventoryValueByWarehouse200,
  GetReportsInventoryValueByWarehouseParams,
  GetReportsSalesCustomersRanking200,
  GetReportsSalesCustomersRankingParams,
  GetReportsSalesDailyTrend200,
  GetReportsSalesDailyTrendParams,
  GetReportsSalesProductsRanking200,
  GetReportsSalesProductsRankingParams,
  GetReportsSalesSummary200,
  GetReportsSalesSummaryParams,
  GetReportsSchedulerStatus200,
  HandlerRefreshAllReportsRequest,
  HandlerRefreshReportRequest,
  PostReportsRefresh200,
  PostReportsRefreshAll200,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getReports = () => {
  /**
   * Get cash flow statement for the specified period
   * @summary Get cash flow statement
   */
  const getReportsFinanceCashFlow = (
    params: GetReportsFinanceCashFlowParams,
    options?: SecondParameter<typeof customInstance<GetReportsFinanceCashFlow200>>
  ) => {
    return customInstance<GetReportsFinanceCashFlow200>(
      { url: `/reports/finance/cash-flow`, method: 'GET', params },
      options
    )
  }
  /**
   * Get detailed cash flow items for the specified period
   * @summary Get cash flow items
   */
  const getReportsFinanceCashFlowItems = (
    params: GetReportsFinanceCashFlowItemsParams,
    options?: SecondParameter<typeof customInstance<GetReportsFinanceCashFlowItems200>>
  ) => {
    return customInstance<GetReportsFinanceCashFlowItems200>(
      { url: `/reports/finance/cash-flow/items`, method: 'GET', params },
      options
    )
  }
  /**
   * Get monthly profit trend for the specified period
   * @summary Get monthly profit trend
   */
  const getReportsFinanceMonthlyTrend = (
    params: GetReportsFinanceMonthlyTrendParams,
    options?: SecondParameter<typeof customInstance<GetReportsFinanceMonthlyTrend200>>
  ) => {
    return customInstance<GetReportsFinanceMonthlyTrend200>(
      { url: `/reports/finance/monthly-trend`, method: 'GET', params },
      options
    )
  }
  /**
   * Get profit analysis by product
   * @summary Get profit by product
   */
  const getReportsFinanceProfitByProduct = (
    params: GetReportsFinanceProfitByProductParams,
    options?: SecondParameter<typeof customInstance<GetReportsFinanceProfitByProduct200>>
  ) => {
    return customInstance<GetReportsFinanceProfitByProduct200>(
      { url: `/reports/finance/profit-by-product`, method: 'GET', params },
      options
    )
  }
  /**
   * Get P&L statement for the specified period
   * @summary Get profit and loss statement
   */
  const getReportsFinanceProfitLoss = (
    params: GetReportsFinanceProfitLossParams,
    options?: SecondParameter<typeof customInstance<GetReportsFinanceProfitLoss200>>
  ) => {
    return customInstance<GetReportsFinanceProfitLoss200>(
      { url: `/reports/finance/profit-loss`, method: 'GET', params },
      options
    )
  }
  /**
   * Get products with low turnover rate
   * @summary Get slow moving products
   */
  const getReportsInventorySlowMoving = (
    params: GetReportsInventorySlowMovingParams,
    options?: SecondParameter<typeof customInstance<GetReportsInventorySlowMoving200>>
  ) => {
    return customInstance<GetReportsInventorySlowMoving200>(
      { url: `/reports/inventory/slow-moving`, method: 'GET', params },
      options
    )
  }
  /**
   * Get aggregated inventory summary
   * @summary Get inventory summary
   */
  const getReportsInventorySummary = (
    params: GetReportsInventorySummaryParams,
    options?: SecondParameter<typeof customInstance<GetReportsInventorySummary200>>
  ) => {
    return customInstance<GetReportsInventorySummary200>(
      { url: `/reports/inventory/summary`, method: 'GET', params },
      options
    )
  }
  /**
   * Get inventory turnover data for products
   * @summary Get inventory turnover
   */
  const getReportsInventoryTurnover = (
    params: GetReportsInventoryTurnoverParams,
    options?: SecondParameter<typeof customInstance<GetReportsInventoryTurnover200>>
  ) => {
    return customInstance<GetReportsInventoryTurnover200>(
      { url: `/reports/inventory/turnover`, method: 'GET', params },
      options
    )
  }
  /**
   * Get inventory value grouped by category
   * @summary Get inventory value by category
   */
  const getReportsInventoryValueByCategory = (
    params: GetReportsInventoryValueByCategoryParams,
    options?: SecondParameter<typeof customInstance<GetReportsInventoryValueByCategory200>>
  ) => {
    return customInstance<GetReportsInventoryValueByCategory200>(
      { url: `/reports/inventory/value-by-category`, method: 'GET', params },
      options
    )
  }
  /**
   * Get inventory value grouped by warehouse
   * @summary Get inventory value by warehouse
   */
  const getReportsInventoryValueByWarehouse = (
    params: GetReportsInventoryValueByWarehouseParams,
    options?: SecondParameter<typeof customInstance<GetReportsInventoryValueByWarehouse200>>
  ) => {
    return customInstance<GetReportsInventoryValueByWarehouse200>(
      { url: `/reports/inventory/value-by-warehouse`, method: 'GET', params },
      options
    )
  }
  /**
   * Triggers manual refresh of a specific report type cache
   * @summary Manually refresh a report cache
   */
  const postReportsRefresh = (
    handlerRefreshReportRequest: HandlerRefreshReportRequest,
    options?: SecondParameter<typeof customInstance<PostReportsRefresh200>>
  ) => {
    return customInstance<PostReportsRefresh200>(
      {
        url: `/reports/refresh`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerRefreshReportRequest,
      },
      options
    )
  }
  /**
   * Triggers manual refresh of all report type caches
   * @summary Refresh all report caches
   */
  const postReportsRefreshAll = (
    handlerRefreshAllReportsRequest: HandlerRefreshAllReportsRequest,
    options?: SecondParameter<typeof customInstance<PostReportsRefreshAll200>>
  ) => {
    return customInstance<PostReportsRefreshAll200>(
      {
        url: `/reports/refresh/all`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlerRefreshAllReportsRequest,
      },
      options
    )
  }
  /**
   * Get top customers by sales for the specified period
   * @summary Get customer sales ranking
   */
  const getReportsSalesCustomersRanking = (
    params: GetReportsSalesCustomersRankingParams,
    options?: SecondParameter<typeof customInstance<GetReportsSalesCustomersRanking200>>
  ) => {
    return customInstance<GetReportsSalesCustomersRanking200>(
      { url: `/reports/sales/customers/ranking`, method: 'GET', params },
      options
    )
  }
  /**
   * Get daily sales trend data for the specified period
   * @summary Get daily sales trend
   */
  const getReportsSalesDailyTrend = (
    params: GetReportsSalesDailyTrendParams,
    options?: SecondParameter<typeof customInstance<GetReportsSalesDailyTrend200>>
  ) => {
    return customInstance<GetReportsSalesDailyTrend200>(
      { url: `/reports/sales/daily-trend`, method: 'GET', params },
      options
    )
  }
  /**
   * Get top products by sales for the specified period
   * @summary Get product sales ranking
   */
  const getReportsSalesProductsRanking = (
    params: GetReportsSalesProductsRankingParams,
    options?: SecondParameter<typeof customInstance<GetReportsSalesProductsRanking200>>
  ) => {
    return customInstance<GetReportsSalesProductsRanking200>(
      { url: `/reports/sales/products/ranking`, method: 'GET', params },
      options
    )
  }
  /**
   * Get aggregated sales summary for the specified period
   * @summary Get sales summary
   */
  const getReportsSalesSummary = (
    params: GetReportsSalesSummaryParams,
    options?: SecondParameter<typeof customInstance<GetReportsSalesSummary200>>
  ) => {
    return customInstance<GetReportsSalesSummary200>(
      { url: `/reports/sales/summary`, method: 'GET', params },
      options
    )
  }
  /**
   * Returns the current status of the report scheduler
   * @summary Get report scheduler status
   */
  const getReportsSchedulerStatus = (
    options?: SecondParameter<typeof customInstance<GetReportsSchedulerStatus200>>
  ) => {
    return customInstance<GetReportsSchedulerStatus200>(
      { url: `/reports/scheduler/status`, method: 'GET' },
      options
    )
  }
  return {
    getReportsFinanceCashFlow,
    getReportsFinanceCashFlowItems,
    getReportsFinanceMonthlyTrend,
    getReportsFinanceProfitByProduct,
    getReportsFinanceProfitLoss,
    getReportsInventorySlowMoving,
    getReportsInventorySummary,
    getReportsInventoryTurnover,
    getReportsInventoryValueByCategory,
    getReportsInventoryValueByWarehouse,
    postReportsRefresh,
    postReportsRefreshAll,
    getReportsSalesCustomersRanking,
    getReportsSalesDailyTrend,
    getReportsSalesProductsRanking,
    getReportsSalesSummary,
    getReportsSchedulerStatus,
  }
}
export type GetReportsFinanceCashFlowResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsFinanceCashFlow']>>
>
export type GetReportsFinanceCashFlowItemsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsFinanceCashFlowItems']>>
>
export type GetReportsFinanceMonthlyTrendResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsFinanceMonthlyTrend']>>
>
export type GetReportsFinanceProfitByProductResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsFinanceProfitByProduct']>>
>
export type GetReportsFinanceProfitLossResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsFinanceProfitLoss']>>
>
export type GetReportsInventorySlowMovingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsInventorySlowMoving']>>
>
export type GetReportsInventorySummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsInventorySummary']>>
>
export type GetReportsInventoryTurnoverResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsInventoryTurnover']>>
>
export type GetReportsInventoryValueByCategoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsInventoryValueByCategory']>>
>
export type GetReportsInventoryValueByWarehouseResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsInventoryValueByWarehouse']>>
>
export type PostReportsRefreshResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['postReportsRefresh']>>
>
export type PostReportsRefreshAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['postReportsRefreshAll']>>
>
export type GetReportsSalesCustomersRankingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsSalesCustomersRanking']>>
>
export type GetReportsSalesDailyTrendResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsSalesDailyTrend']>>
>
export type GetReportsSalesProductsRankingResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsSalesProductsRanking']>>
>
export type GetReportsSalesSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsSalesSummary']>>
>
export type GetReportsSchedulerStatusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getReports>['getReportsSchedulerStatus']>>
>
