/**
 * // This file is auto-generated by orval
 * // Do not edit manually
 *
 */
import type {
  DeleteTradePurchaseReturnsIdBody,
  DeleteTradePurchaseReturnsIdItemsItemId200,
  DeleteTradePurchaseReturnsIdItemsItemIdBody,
  GetTradePurchaseReturns200,
  GetTradePurchaseReturnsBody,
  GetTradePurchaseReturnsId200,
  GetTradePurchaseReturnsIdBody,
  GetTradePurchaseReturnsNumberReturnNumber200,
  GetTradePurchaseReturnsNumberReturnNumberBody,
  GetTradePurchaseReturnsParams,
  GetTradePurchaseReturnsStatsSummary200,
  GetTradePurchaseReturnsStatsSummaryBody,
  PostTradePurchaseReturns201,
  PostTradePurchaseReturnsBody,
  PostTradePurchaseReturnsIdApprove200,
  PostTradePurchaseReturnsIdApproveBody,
  PostTradePurchaseReturnsIdCancel200,
  PostTradePurchaseReturnsIdCancelBody,
  PostTradePurchaseReturnsIdComplete200,
  PostTradePurchaseReturnsIdCompleteBody,
  PostTradePurchaseReturnsIdItems200,
  PostTradePurchaseReturnsIdItemsBody,
  PostTradePurchaseReturnsIdReject200,
  PostTradePurchaseReturnsIdRejectBody,
  PostTradePurchaseReturnsIdShip200,
  PostTradePurchaseReturnsIdShipBody,
  PostTradePurchaseReturnsIdSubmit200,
  PostTradePurchaseReturnsIdSubmitBody,
  PutTradePurchaseReturnsId200,
  PutTradePurchaseReturnsIdBody,
  PutTradePurchaseReturnsIdItemsItemId200,
  PutTradePurchaseReturnsIdItemsItemIdBody,
} from '.././models'

import { customInstance } from '../../services/axios-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getPurchaseReturns = () => {
  /**
   * Retrieve a paginated list of purchase returns with optional filtering
   * @summary List purchase returns
   */
  const getTradePurchaseReturns = (
    getTradePurchaseReturnsBody: GetTradePurchaseReturnsBody,
    params?: GetTradePurchaseReturnsParams,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseReturns200>>
  ) => {
    return customInstance<GetTradePurchaseReturns200>(
      {
        url: `/trade/purchase-returns`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        params,
      },
      options
    )
  }
  /**
   * Create a new purchase return from an existing purchase order
   * @summary Create a new purchase return
   */
  const postTradePurchaseReturns = (
    postTradePurchaseReturnsBody: PostTradePurchaseReturnsBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturns201>>
  ) => {
    return customInstance<PostTradePurchaseReturns201>(
      {
        url: `/trade/purchase-returns`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsBody,
      },
      options
    )
  }
  /**
   * Delete a purchase return (only allowed in DRAFT status)
   * @summary Delete a purchase return
   */
  const deleteTradePurchaseReturnsId = (
    id: string,
    deleteTradePurchaseReturnsIdBody: DeleteTradePurchaseReturnsIdBody,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      {
        url: `/trade/purchase-returns/${id}`,
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        data: deleteTradePurchaseReturnsIdBody,
      },
      options
    )
  }
  /**
   * Retrieve a purchase return by its ID
   * @summary Get purchase return by ID
   */
  const getTradePurchaseReturnsId = (
    id: string,
    getTradePurchaseReturnsIdBody: GetTradePurchaseReturnsIdBody,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseReturnsId200>>
  ) => {
    return customInstance<GetTradePurchaseReturnsId200>(
      {
        url: `/trade/purchase-returns/${id}`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      },
      options
    )
  }
  /**
   * Update a purchase return (only allowed in DRAFT status)
   * @summary Update a purchase return
   */
  const putTradePurchaseReturnsId = (
    id: string,
    putTradePurchaseReturnsIdBody: PutTradePurchaseReturnsIdBody,
    options?: SecondParameter<typeof customInstance<PutTradePurchaseReturnsId200>>
  ) => {
    return customInstance<PutTradePurchaseReturnsId200>(
      {
        url: `/trade/purchase-returns/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: putTradePurchaseReturnsIdBody,
      },
      options
    )
  }
  /**
   * Approve a purchase return (transitions from PENDING to APPROVED)
   * @summary Approve a purchase return
   */
  const postTradePurchaseReturnsIdApprove = (
    id: string,
    postTradePurchaseReturnsIdApproveBody: PostTradePurchaseReturnsIdApproveBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturnsIdApprove200>>
  ) => {
    return customInstance<PostTradePurchaseReturnsIdApprove200>(
      {
        url: `/trade/purchase-returns/${id}/approve`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsIdApproveBody,
      },
      options
    )
  }
  /**
   * Cancel a purchase return (from DRAFT, PENDING, or APPROVED status - before shipping)
   * @summary Cancel a purchase return
   */
  const postTradePurchaseReturnsIdCancel = (
    id: string,
    postTradePurchaseReturnsIdCancelBody: PostTradePurchaseReturnsIdCancelBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturnsIdCancel200>>
  ) => {
    return customInstance<PostTradePurchaseReturnsIdCancel200>(
      {
        url: `/trade/purchase-returns/${id}/cancel`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsIdCancelBody,
      },
      options
    )
  }
  /**
   * Mark a purchase return as completed after supplier confirms receipt (transitions from SHIPPED to COMPLETED)
   * @summary Complete a purchase return
   */
  const postTradePurchaseReturnsIdComplete = (
    id: string,
    postTradePurchaseReturnsIdCompleteBody: PostTradePurchaseReturnsIdCompleteBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturnsIdComplete200>>
  ) => {
    return customInstance<PostTradePurchaseReturnsIdComplete200>(
      {
        url: `/trade/purchase-returns/${id}/complete`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsIdCompleteBody,
      },
      options
    )
  }
  /**
   * Add a new item to a purchase return (only allowed in DRAFT status)
   * @summary Add item to purchase return
   */
  const postTradePurchaseReturnsIdItems = (
    id: string,
    postTradePurchaseReturnsIdItemsBody: PostTradePurchaseReturnsIdItemsBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturnsIdItems200>>
  ) => {
    return customInstance<PostTradePurchaseReturnsIdItems200>(
      {
        url: `/trade/purchase-returns/${id}/items`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsIdItemsBody,
      },
      options
    )
  }
  /**
   * Remove an item from a purchase return (only allowed in DRAFT status)
   * @summary Remove item from purchase return
   */
  const deleteTradePurchaseReturnsIdItemsItemId = (
    id: string,
    itemId: string,
    deleteTradePurchaseReturnsIdItemsItemIdBody: DeleteTradePurchaseReturnsIdItemsItemIdBody,
    options?: SecondParameter<typeof customInstance<DeleteTradePurchaseReturnsIdItemsItemId200>>
  ) => {
    return customInstance<DeleteTradePurchaseReturnsIdItemsItemId200>(
      {
        url: `/trade/purchase-returns/${id}/items/${itemId}`,
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        data: deleteTradePurchaseReturnsIdItemsItemIdBody,
      },
      options
    )
  }
  /**
   * Update an item in a purchase return (only allowed in DRAFT status)
   * @summary Update return item
   */
  const putTradePurchaseReturnsIdItemsItemId = (
    id: string,
    itemId: string,
    putTradePurchaseReturnsIdItemsItemIdBody: PutTradePurchaseReturnsIdItemsItemIdBody,
    options?: SecondParameter<typeof customInstance<PutTradePurchaseReturnsIdItemsItemId200>>
  ) => {
    return customInstance<PutTradePurchaseReturnsIdItemsItemId200>(
      {
        url: `/trade/purchase-returns/${id}/items/${itemId}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: putTradePurchaseReturnsIdItemsItemIdBody,
      },
      options
    )
  }
  /**
   * Reject a purchase return (transitions from PENDING to REJECTED)
   * @summary Reject a purchase return
   */
  const postTradePurchaseReturnsIdReject = (
    id: string,
    postTradePurchaseReturnsIdRejectBody: PostTradePurchaseReturnsIdRejectBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturnsIdReject200>>
  ) => {
    return customInstance<PostTradePurchaseReturnsIdReject200>(
      {
        url: `/trade/purchase-returns/${id}/reject`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsIdRejectBody,
      },
      options
    )
  }
  /**
   * Mark a purchase return as shipped back to supplier (transitions from APPROVED to SHIPPED, triggers inventory deduction)
   * @summary Ship a purchase return
   */
  const postTradePurchaseReturnsIdShip = (
    id: string,
    postTradePurchaseReturnsIdShipBody: PostTradePurchaseReturnsIdShipBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturnsIdShip200>>
  ) => {
    return customInstance<PostTradePurchaseReturnsIdShip200>(
      {
        url: `/trade/purchase-returns/${id}/ship`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsIdShipBody,
      },
      options
    )
  }
  /**
   * Submit a purchase return for approval (transitions from DRAFT to PENDING)
   * @summary Submit a purchase return for approval
   */
  const postTradePurchaseReturnsIdSubmit = (
    id: string,
    postTradePurchaseReturnsIdSubmitBody: PostTradePurchaseReturnsIdSubmitBody,
    options?: SecondParameter<typeof customInstance<PostTradePurchaseReturnsIdSubmit200>>
  ) => {
    return customInstance<PostTradePurchaseReturnsIdSubmit200>(
      {
        url: `/trade/purchase-returns/${id}/submit`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postTradePurchaseReturnsIdSubmitBody,
      },
      options
    )
  }
  /**
   * Retrieve a purchase return by its return number
   * @summary Get purchase return by return number
   */
  const getTradePurchaseReturnsNumberReturnNumber = (
    returnNumber: string,
    getTradePurchaseReturnsNumberReturnNumberBody: GetTradePurchaseReturnsNumberReturnNumberBody,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseReturnsNumberReturnNumber200>>
  ) => {
    return customInstance<GetTradePurchaseReturnsNumberReturnNumber200>(
      {
        url: `/trade/purchase-returns/number/${returnNumber}`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      },
      options
    )
  }
  /**
   * Get count of returns by status for dashboard
   * @summary Get return status summary
   */
  const getTradePurchaseReturnsStatsSummary = (
    getTradePurchaseReturnsStatsSummaryBody: GetTradePurchaseReturnsStatsSummaryBody,
    options?: SecondParameter<typeof customInstance<GetTradePurchaseReturnsStatsSummary200>>
  ) => {
    return customInstance<GetTradePurchaseReturnsStatsSummary200>(
      {
        url: `/trade/purchase-returns/stats/summary`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      },
      options
    )
  }
  return {
    getTradePurchaseReturns,
    postTradePurchaseReturns,
    deleteTradePurchaseReturnsId,
    getTradePurchaseReturnsId,
    putTradePurchaseReturnsId,
    postTradePurchaseReturnsIdApprove,
    postTradePurchaseReturnsIdCancel,
    postTradePurchaseReturnsIdComplete,
    postTradePurchaseReturnsIdItems,
    deleteTradePurchaseReturnsIdItemsItemId,
    putTradePurchaseReturnsIdItemsItemId,
    postTradePurchaseReturnsIdReject,
    postTradePurchaseReturnsIdShip,
    postTradePurchaseReturnsIdSubmit,
    getTradePurchaseReturnsNumberReturnNumber,
    getTradePurchaseReturnsStatsSummary,
  }
}
export type GetTradePurchaseReturnsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['getTradePurchaseReturns']>>
>
export type PostTradePurchaseReturnsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturns']>>
>
export type DeleteTradePurchaseReturnsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['deleteTradePurchaseReturnsId']>>
>
export type GetTradePurchaseReturnsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['getTradePurchaseReturnsId']>>
>
export type PutTradePurchaseReturnsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['putTradePurchaseReturnsId']>>
>
export type PostTradePurchaseReturnsIdApproveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturnsIdApprove']>>
>
export type PostTradePurchaseReturnsIdCancelResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturnsIdCancel']>>
>
export type PostTradePurchaseReturnsIdCompleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturnsIdComplete']>>
>
export type PostTradePurchaseReturnsIdItemsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturnsIdItems']>>
>
export type DeleteTradePurchaseReturnsIdItemsItemIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPurchaseReturns>['deleteTradePurchaseReturnsIdItemsItemId']>
  >
>
export type PutTradePurchaseReturnsIdItemsItemIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['putTradePurchaseReturnsIdItemsItemId']>>
>
export type PostTradePurchaseReturnsIdRejectResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturnsIdReject']>>
>
export type PostTradePurchaseReturnsIdShipResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturnsIdShip']>>
>
export type PostTradePurchaseReturnsIdSubmitResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['postTradePurchaseReturnsIdSubmit']>>
>
export type GetTradePurchaseReturnsNumberReturnNumberResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPurchaseReturns>['getTradePurchaseReturnsNumberReturnNumber']>
  >
>
export type GetTradePurchaseReturnsStatsSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPurchaseReturns>['getTradePurchaseReturnsStatsSummary']>>
>
